### ISSUE TITLE
PromptSupport can get fooled if same text is typed

### ISSUE THREAD

**Issue by wimjongman** [EclipseNebula/nebula#10]
Opal PromptSupport does not know when the user typed the same text as the initial prompt text. PromptSupport may only show the prompt if the underlying text widget is actually empty.

**Comment by lcaron** [comment]
Hi Wim,
If I understand well, if one type the same text than the "prompted" text, the prompted text is displayed ?

**Comment by wimjongman** [comment]
Then the prompt support thinks that nothing was typed and clears the text on focus lost.

**Comment by lcaron** [comment]
Ok thanks

**Comment by lcaron** [comment]
Issue merged and closed
