### ISSUE TITLE
Create Floating Text Widget

### ISSUE THREAD

**Issue by wimjongman** [EclipseNebula/nebula#11]
Create a Floating Text widget which is common in mobile applications.

Instances of this class are selectable user interface objects that allow the 
user to enter and modify text with a label floating above the input area.    
FloatingText controls can be either single or multi-line. In contrast to a    
Text widget, when a floating text control is created with a border, a custom 
drawn inset will be painted INSTEAD OF the platform specific inset.          

### Styles are inherited from Text and subclasses:              
CENTER, ICON_CANCEL, ICON_SEARCH, LEFT, MULTI, PASSWORD, SEARCH, SINGLE, 
RIGHT, READ_ONLY, WRAP, BORDER, H_SCROLL, V_SCROLL, LEFT_TO_RIGT,            
RIGHT_TO_LEFT, FLIP_TEXT_DIRECTION

**Comment by wimjongman** [comment]
@vogella please take a look.

**Comment by wimjongman** [comment]
![2018-10-26_22-05-47](https://user-images.githubusercontent.com/180969/47590048-5aa08f00-d96b-11e8-8c8e-d6ab4b119c13.gif)

**Comment by mickaelistria** [comment]
I like it a lot! Does it behave well with screen readers and accessibility in general?

**Comment by vogella** [comment]
Looks awesome! Thanks, Win.

Mickael Istria <notifications@github.com> schrieb am So., 28. Okt. 2018,
16:43:

**Comment by wimjongman** [comment]
> I like it a lot! Does it behave well with screen readers and accessibility in general?

I have no idea. I hacked it in a couple of hours. But you gave me an idea to use a label as the top element instead of a composite.

**Comment by wimjongman** [comment]
> 
> 
> > I like it a lot! Does it behave well with screen readers and accessibility in general?
> 
> I have no idea. I hacked it in a couple of hours. But you gave me an idea to use a label as the top element instead of a composite.

It does now ;)

**Comment by wimjongman** [comment]
![2018-10-31_19-48-51](https://user-images.githubusercontent.com/180969/47811430-0ff58d00-dd46-11e8-943c-39d9a08d9855.gif)

**Comment by vogella** [comment]
Wim, this looks awesome. How about using this widget in our  wizard, e.g., the New Project wizard. Might give Eclipse a "fresh" feeling.

![new project _734](https://user-images.githubusercontent.com/139910/47842757-eed08300-ddbd-11e8-9e69-e054b1d39d19.png)

**Comment by tomsontom** [comment]
Hi,

I don‘t think this would be a good idea. The platform UI needs to be consistent and the platform has beside that the rule to not depend on stuff out the platform like nebula.

Tom 

Von meinem iPhone gesendet

**Comment by vogella** [comment]
We could consistently update the wizards and the rule could be changed if we think this makes sense. Or we could move the widget to JFace or SWT.

**Comment by wimjongman** [comment]
I guess we have to move it then but we have to be very careful. I agree with both of you. 

First need to make sure that the widget is behaving well on all supported platforms and in theming and in HDPI and in large text environments. That is not so simple.

Fortunately, the widget is childishly simple. It is just a composite with a stacked label/text. So that is good. It also works with prompt support from Opal which has at least one flaw that might be fine for a RCP client but not for platform. So we need to either remove that dependency or change it.

However, there is no harm in making a little prototype. I will see if I can make this happen.

**Comment by wimjongman** [comment]
![2018-12-19_09-56-21](https://user-images.githubusercontent.com/180969/50210405-4e86eb80-0376-11e9-8227-43164588d0d0.gif)

**Comment by wimjongman** [comment]
Bug 532680 - Create a new floating text widget

Resolved

**Comment by wimjongman** [comment]
@vogella 

![2018-12-21_00-17-40](https://user-images.githubusercontent.com/180969/50316223-0838a600-04b6-11e9-83af-d4e9bf7dc100.gif)

**Comment by vogella** [comment]
Thanks Wim for this. In this prototype I find it confusing that the same font is used for "Hint" and "Real text". I would suggest to use a "gray and smaller" font for the hint. Also the small line between Hint and Real text does not look good to me.
