### ISSUE TITLE
Notifier examples look bad on Linux

### ISSUE THREAD

**Issue by vogella** [EclipseNebula/nebula#192]
See screenshot

![image](https://user-images.githubusercontent.com/139910/70128373-f88d7f80-167c-11ea-84a8-333f0eee9eab.png)

**Comment by lcaron** [comment]
Hi Lars
I"ve tried on Fedora with OpenJDK 11, and I could not reproduce this problem. Can you give me your configuration ?
Laurent

**Comment by lcaron** [comment]
Hi Lars
I've made a modification, can you tell me if it is better now ?
Thanks,
Laurent

**Comment by lcaron** [comment]
Please reopen it if necessary
