### ISSUE TITLE
GeoMap - Concurrency Issues

### ISSUE THREAD

**Issue by JackPGreen** [EclipseNebula/nebula#196]
If you set the map cache size to a low value (e.g. 0, 1, 5 etc), the map tiles do not load.

If you add a Thread.sleep to the paintTile method, they then work again.

This suggests that it's not the cache size that's the problem, but some kind of race condition where if something happens too quickly, it breaks. My suspicion is that it's drawing the picture before the image has actually loaded.

**Comment by wimjongman** [comment]
Hey Jack. Are you able to provide patches? We would love to see someone take this widget to the next level.

**Comment by JackPGreen** [comment]
> Hey Jack. Are you able to provide patches? We would love to see someone take this widget to the next level.

Unfortunately I am not sure what the problem is so I am not able to suggest a fix. Sorry.

**Comment by lcaron** [comment]
Jack,
I had a look. The cache has a "_cleaning method_" that remove old elements so the cache size is always lower or equals to the initial size.

When the initial size is too little (let say 1 element), when a tile is displayed one element is added to the cache... and the previous one is erased, and will not be drawed once the element is loaded.

To fix this problem we should forbid developers to use a too little value to initial size.

**Comment by lcaron** [comment]
Problem fixed. If the initial size is lower than 200 (arbitrary value) an exception is thrown
