### ISSUE TITLE
Make the text widget gray when the multichoice is not editable

### ISSUE THREAD

**Issue by Filterer** [EclipseNebula/nebula#212]
Our users are trying to type in the text field but its not writable while the text color is white so its a bit confusing. It would be nice when the multichoice is read-only to make the text also gray just like when you use the setEditable method to false on a text or combo widget.

**Comment by lcaron** [comment]
Hi
I'm gonna have a look on it, can you please provide a snippet that reproduces the problem ?
Laurent

**Comment by Filterer** [comment]
Thanks for the fast answer. I would like the multichoice widget to have the setEditable method available just like the Text class has it, if you don't want to expose the text of the multichoice itself.

![multichoice example](https://user-images.githubusercontent.com/29089566/74248005-3cd57580-4ce7-11ea-9cab-1d6a96950b8b.jpg)

In this example, the object type multichoice should look like the labels one. Both of them are not editable but the user can click on them and move with the arrow keys left and right to see the available values so this is fine. The labels widget is not a multichoice one, its a text and a button that I made them look like that.

The point is that if its white its misleading that its editable while its not.

**Comment by lcaron** [comment]
To keep tracking, I've filled a bug in Bugzilla : https://bugs.eclipse.org/bugs/show_bug.cgi?id=560043

**Comment by lcaron** [comment]
This bug is now fixed : the method `setEditable()` has been added, and when the widget is not enabled the look is the same as your screenshot.

Thank you for reporting this feature.

**Comment by Filterer** [comment]
Thank you for the fast fix and for the nice widget :)

**Comment by lcaron** [comment]
Thank you for reporting and using Multichoice ;)
