### ISSUE TITLE
GeoMap - Zoom listener fired before MapPosition has been updated

### ISSUE THREAD

**Issue by JackPGreen** [EclipseNebula/nebula#218]
In `GeoMapUtil.zoomOut`, `geoMap.setZoom` is called, which updates the zoom level and then calls `fireZoomChanged()`, which causes the listeners to respond to a change in the zoom.

The problem is that the map position is only updated in `GeoMapUtil.zoomOut` after the `geoMap.setZoom` call - which means any listeners responding to the zoom change will be using an outdated map position.

I think in `zoomIn` & `zoomOut` the statements should simply be switched in order.

**Comment by wimjongman** [comment]
Sounds great. Do you care to make that change, test it and then file pull request?

**Comment by JackPGreen** [comment]
Hi,

I've raised a pull request for the above change.

**Comment by wimjongman** [comment]
Tracked by: [Bug 560841](https://bugs.eclipse.org/bugs/show_bug.cgi?id=560841) - GeoMap - Zoom listener fired before MapPosition has been updated
