### ISSUE TITLE
GeoMap - Specify a Minimum Zoom Level

### ISSUE THREAD

**Issue by JackPGreen** [EclipseNebula/nebula#241]
In org.eclipse.nebula.widgets.geomap.TileServer, a maximum zoom level is specified.

Some Tile Servers - e.g. Ordnance Survey's Maps API - specify a minimum zoom level, too - https://osdatahub.os.uk/docs/wmts/technicalSpecification

Currently the minimum zoom level is hard-coded to 0.

I think this should be dynamic.

**Comment by wimjongman** [comment]
I agree. That would be a nice feature.

**Comment by lcaron** [comment]
Jack I've reviewed the commit, and it is ok for me. Can you please create a Pull Request ?

**Comment by JackPGreen** [comment]
@lcaron 

See https://github.com/eclipse/nebula/pull/242

**Comment by wimjongman** [comment]
@JackPGreen Jack there are some issues with the PR. Can you please rebase?

**Comment by lcaron** [comment]
Bug fixed, thanks to @JackPGreen for the patch !

**Comment by JackPGreen** [comment]
And thanks @lcaron for the merge 👍
