### ISSUE TITLE
RoundedSwitch does not notify SelectionListener's on changes

### ISSUE THREAD

**Issue by borlander** [EclipseNebula/nebula#248]
Sorry if I missed something, but I believe that the new RoundedSwitch lacks the code that actually broadcasts the selection event. 

see https://github.com/eclipse/nebula/blob/080ffe8d04f416f0bcff6e66876627f7836645d3/widgets/roundedswitch/org.eclipse.nebula.widgets.roundedswitch/src/org/eclipse/nebula/widgets/roundedswitch/RoundedSwitch.java#L377

**Comment by lcaron** [comment]
Hi

OMG !!! You are totally right. I've opened the bug
https://bugs.eclipse.org/bugs/show_bug.cgi?id=566102

I'm gonna fix it today

Thank you for your feedback,

Laurent

**Comment by lcaron** [comment]
This problem has been fixed.

Have a nice day,

Laurent

Le dim. 16 août 2020 à 12:58, Laurent Caron <laurent.caron@gmail.com> a
écrit :
