### ISSUE TITLE
 Bug 567735 - SvgLoader's parsePathData does not handle multi-valued commands 

### ISSUE THREAD

**Issue by edward-k-francis** [EclipseNebula/nebula#251]
According to the SVG specification (https://svgwg.org/specs/paths/#PathData), the path data for all commands could have multiple values.  For example, when drawing a line:

> Draw a line from the current point to the given (x,y) coordinate which becomes the new current point. L (uppercase) indicates that absolute coordinates will follow; l (lowercase) indicates that relative coordinates will follow. **_A number of coordinates pairs may be specified to draw a polyline._** At the end of the command, the new current point is set to the final set of coordinates provided.

The current method ignores any additional coordinate pairs.  The multi-values are applicable to all commands except 'Z' ('z') and 'A' ('a').  'M' ('m") is a special case and any additional coordinate pairs should be treated as 'L' ('l').

**Comment by edward-k-francis** [comment]
I've forked the code and have put a code change in a branch of the fork if you would like to look at it.

**Comment by lcaron** [comment]
Sure edward !

Please create a PR and I'll have a look.

Laurent

**Comment by edward-k-francis** [comment]
@lcaron, PR has been created.

**Comment by lcaron** [comment]
Hi
Your PR is OK for me. In order to merge it, you have to sign the Eclipse Contributor Agreement by creating a new account :
[](https://accounts.eclipse.org/user/register)

Please inform us when it's done.

Laurent

**Comment by wimjongman** [comment]
I don't think SVG support is a first-class citizen in Nebula at the moment. It seems hidden inside cwt which was meant to be a common set of graphic tools for all widgets. Some widgets use cwt but most widgets don't.

Is it an idea to pull svg support out of cwt and into its own widget? @edward-k-francis is this something you would be interested in working on?

**Comment by edward-k-francis** [comment]
I would be interested. Are you thinking that the svg package becomes some sort of library project that could be consumed by more than just Nebula?

**Comment by wimjongman** [comment]
Yes, exactly. I filed a Bugzilla [1] where we can discuss the approach and requirements. Did you read the contribution guide? If not then maybe this is a good time [2] :)

[1] https://bugs.eclipse.org/bugs/show_bug.cgi?id=566565
[2] https://wiki.eclipse.org/Nebula/Contributions
