### ISSUE TITLE
SvgLoader does not handle relative points correctly for Bézier commands

### ISSUE THREAD

**Issue by edward-k-francis** [EclipseNebula/nebula#256]
According to the specification all points within a relative Bézier command (e.g. 'c','s','q','t'), are all relative to the current point.  

>When a relative c or s command is used, each of the relative coordinate pairs is computed as for those in an m command. For example, the final control point of the curve of both commands is (cpx + x cos cb + y sin cb, cpy + x sin cb + y cos cb).  [Where cpx and cpy represent the coordinates of the current point,and cb represents the current bearing.]

Currently the code makes each point of the Bézier command relative to the last two values added including those from the current command.

**Comment by edward-k-francis** [comment]
PR created.

**Comment by wimjongman** [comment]
Edward
