### ISSUE TITLE
Nebula PreferenceWindow should use action orientated button instead of OK and Cancel

### ISSUE THREAD

**Issue by vogella** [EclipseNebula/nebula#265]
PreferenceWindow#buildButtons uses Ok and Cancel. Maybe these default text value coudl be "Apply" or "Close" or "Apply and Close" for the OK button?

**Comment by lcaron** [comment]
Very good idea, I'll work on it !

**Comment by vogella** [comment]
Cool. Thanks

**Comment by lcaron** [comment]
This bug has been fixed in the next release of Nebula.

Thank you Lars for the suggest !
