### ISSUE TITLE
Preference Window opens on wrong screen

### ISSUE THREAD

**Issue by vogella** [EclipseNebula/nebula#266]
I think it is better if the preference window opens on the same screen as the running application. Currently it seems to use the laptop (I guess the primary screen) and not the screen on which my application is running.

Looks like this is done in SWTGraphicUtil in PreferenceWindow#openShell

**Comment by lcaron** [comment]
You're totally wright, I'll work on it

**Comment by vogella** [comment]
Thanks!

**Comment by lcaron** [comment]
This bug should have been fixed in the next release of Nebula.

@vogella I've just one monitor, can you please tell me if it is ok ?
