### ISSUE TITLE
PWFontChooser does not show font information at initialization

### ISSUE THREAD

**Issue by Bauer-David** [EclipseNebula/nebula#267]
I try to use the FontChooser in my PreferenceWindow, but it doesn't display the value bound to the property key. 

https://github.com/eclipse/nebula/blob/f8ea050c83a78e58255076c97d7d66c007ae3327/widgets/opal/preferencewindow/org.eclipse.nebula.widgets.opal.preferencewindow/src/org/eclipse/nebula/widgets/opal/preferencewindow/widgets/PWFontChooser.java#L71

in the referenced line, the following code should be added

	text.setText(buildFontInformation());

**Comment by lcaron** [comment]
This bug has been fixed in the next release of Nebula. 
Thank you @BADMinova for the fix !
