### ISSUE TITLE
RichTextPainter calculates wrong height

### ISSUE THREAD

**Issue by BeckitBenkster** [EclipseNebula/nebula#27]
The problem has already been described here:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=541345

I will copy the discussion in here anyway:
> Tommy Redel
> 
> Hello,
> 
> when I use a list followed by text in a RichTextCellPainter the resulting calculated preferred row height is wrong.
> 
> The cleaned HTML in the RichTextPainter looks as follows:
> `<root><ul><li>Line1</li></ul>Test</root>`
> 
> In the paintHTML method of the RichTextPainter this will result in just a single line. So the LinePainter will just be asked once assuming there is just one single line.
> 
> When the content is painted, everything looks fine. So the list with the single item gets its own line and the Text "Test" gets a second line.
> 
> So this is just a problem when caluclating the preferred row height.
> 
> Greetings
> Tommy
---
> Dirk Fauth
> 
> I just noticed that the issue is not in NatTable, it is in the RichTextPainter of the Nebula project.
> 
> You need to create an issue with the Nebula project. As the Nebula project has moved to GitHub, you should create an issue there and provide a pull request to fix this.
> 
> https://github.com/eclipse/nebula
> 
> IMHO the issue is that on handling the end tag of the unordered list, the currentLine variable is not set to null. Therefore the the calculation takes the following characters as part of the last line of the list.
> 
> By adding the following lines at the end of the case block (line 392) the issue should be fixed.
> 
> // set currentLine to null as any further content will start on a new line
currentLine = null;
> 
> I will close the ticket here as WONTFIX, as it is not NatTable and Nebula now uses GitHub issues for bug tracking. You can copy my answer there and provide a pull request to fix this. Hopefully this does not brake anything else. But in theory this should be the correct handling. In HTML there will be always a new line if something comes after a list end tag.

**Comment by fipro78** [comment]
Fixed, please verify
