### ISSUE TITLE
PasswordRevealer cannot be used as drop-in replacement for Text widgets

### ISSUE THREAD

**Issue by vogella** [EclipseNebula/nebula#281]
I tried using PasswordRevealer  as drop-in replacement for a text field but it seems to have confuse the layout:

Original:
Text password = new Text(container, SWT.BORDER | SWT.PASSWORD);
Text password.setLayoutData(GridDataFactory.fillDefaults().hint(130, SWT.DEFAULT).span(2, 1).create());.

![label](https://user-images.githubusercontent.com/139910/99548399-e6edd680-29b8-11eb-94c3-34a56fe6ae68.PNG)

After changing the code:

PasswordRevealer password = new PasswordRevealer(parent, SWT.BORDER);
password.setLayoutData(GridDataFactory.fillDefaults().hint(130, SWT.DEFAULT).span(2, 1).create());

![password](https://user-images.githubusercontent.com/139910/99548327-d0e01600-29b8-11eb-91e2-ad8e196a929d.PNG)

Maybe it modifies the layout on the parent?

**Comment by lcaron** [comment]
Hi Lars

I fixed my code and my tests are OK. Can you tell me if it is better ?

**Comment by vogella** [comment]
Thanks, Laurent. Behavior is much better. I see other issues but I open new bugs for these.

**Comment by lcaron** [comment]
Great news, I'll fix other issues ASAP
