### ISSUE TITLE
PasswordRevealer - Button has background

### ISSUE THREAD

**Issue by vogella** [EclipseNebula/nebula#284]
If possible the background of the PWR should be transparent, otherwise it looks strange.

![image](https://user-images.githubusercontent.com/139910/100206809-1778c780-2f07-11eb-8673-a890310b5926.png)

**Comment by lcaron** [comment]
Lars, can you please post the code of this composite ?

**Comment by lcaron** [comment]
Bug fixed in the latest release of Nebula (nightly and stable)
