### ISSUE TITLE
PasswordRevealer Option to show pw after mouse click without holding the mouse

### ISSUE THREAD

**Issue by vogella** [EclipseNebula/nebula#285]
AFAICS the PasswordRevealer  shows only the PW if the user continues to hold the mouse button. I think most websites react differently. If you select "Show password" it shows the PW until the user selects this option again.

Can this also be provided by PasswordRevealer? Maybe even as default as I think this is what the user expects (I might be wrong here).

**Comment by lcaron** [comment]
Hi Lars

You're totally right: the PasswordRevealer mimics the behaviour of the login page on Windows. It is a good idea to let the developper choose the way password is revealed (on press or like a radio button)

**Comment by lcaron** [comment]
Lars,

The behaviour you asked can be implemented by using the flag SWT.PUSH.
I've also updated the documentation.

**Comment by vogella** [comment]
Thanks you
