### ISSUE TITLE
Grid inside Scrollable Composite draws outside its bounds on Linux GTK

### ISSUE THREAD

**Issue by MrTimbones** [EclipseNebula/nebula#286]
When a Grid is placed inside of a ScrollableComposite, then the grid contents are sometimes rendered outside of the area of the scrollable. This is most noticeable on the initial creation, and when resizing the entire window. Scrolling the grid stays within the bounds, but leaves a mess outside of the scrollable.

![ScrollableGridTest-issue](https://user-images.githubusercontent.com/75039652/100268157-7e6c9f80-2f4c-11eb-938d-8e84721d8104.png) --- should be --> ![ScrollableGridTest-with-fix](https://user-images.githubusercontent.com/75039652/100268195-8e847f00-2f4c-11eb-9d9f-b0f8969a9c26.png)

_Test code that demonstrates this: [ScrollableGridTest.java.txt](https://github.com/eclipse/nebula/files/5598627/ScrollableGridTest.java.txt)_

Discovered on Linux with GTK (Ubuntu 20.04), and yet not a problem on Windows. This used to be fine on older SWT/GTK (Eclipse 3.8) and issue has surfaced since moving to a newer platform (i.e. Eclipse 4.1x). Perhaps something changed within GTK 3?

I think this may be due to the calls to **gc.setClipping()** in onPaint() before calling the paint() method of the cell renderer, as these are ignoring the clipping from the paint event.

I was able to fix it by saving the original clipping at the top of the function, and then replacing `gc.setClipping(new Rectangle(...))` with `gc.setClipping(originalClipping.intersection(new Rectangle(...)))`. This ensures that the clipping is never set to be outside that of the paint event. See [Grid.diff.txt](https://github.com/eclipse/nebula/files/5598703/Grid.diff.txt). Might need to do something with insertMarkPosFound block too.

**Comment by wimjongman** [comment]
It looks like you know what you are doing, Tim. Please provide a pull request if you can.

**Comment by lcaron** [comment]
The Pull Request has been merged. Thank you very much Tim for you analysis and fix.

**Comment by MrTimbones** [comment]
Thank you for merging quickly, much appreciated.

**Comment by wimjongman** [comment]
Did someone test this on Windows/Mac?

**Comment by lcaron** [comment]
I did on Windows 10 (with Eclipse Oxygen and 2020-09) and MacOSX Big Sur (Eclipse 2020-09), that's why I closed the bug

**Comment by MrTimbones** [comment]
I have tested both my test program and my application with org.eclipse.nebula.widgets.grid_1.1.0.202011271839.jar on Ubuntu 18.04.5 and Windows 10, and it's working well. Thanks.

**Comment by wimjongman** [comment]
Awesome! Thanks, Laurent. I should not have asked :) 👍

**Comment by wimjongman** [comment]
> I have tested both my test program and my application with 

Thanks, Tim!! We are looking forward to seeing more from you! Congratulations on your first Eclipse/Github commit. The Grid is a very popular widget so your code will be running in a lot of applications.

The latest snapshot can be downloaded here:

https://download.eclipse.org/nebula/snapshot/
