### ISSUE TITLE
TextAssist widget is not useable

### ISSUE THREAD

**Issue by jolkdarr** [EclipseNebula/nebula#290]
Hi

The popup window appears fleetingly and is quickly closed.
I tried the provided snippet. The same result is observed.

Environment: Linux, GTK3.

**Comment by lcaron** [comment]
Bonjour

I've fixed this problem, it will be available in the next _nightly build_  : http://download.eclipse.org/nebula/snapshot

Thank you for your feedback,

Laurent

**Comment by jolkdarr** [comment]
Good news! 🎅
Thanks for the quick fix. 🎁
