### ISSUE TITLE
org.eclipse.nebula.widgets.opal.dialog.Dialog.center() should fall back to provided shell

### ISSUE THREAD

**Issue by laeubi** [EclipseNebula/nebula#294]
org.eclipse.nebula.widgets.opal.dialog.Dialog.center() has the following code

```
		if (centerPolicy == CenterOption.CENTER_ON_SCREEN || shell.getParent() == null) {
			Shell activeShell = shell.getDisplay().getActiveShell();
			final Rectangle monitorBounds = SWTGraphicUtil.getBoundsOfMonitorOnWhichShellIsDisplayed(activeShell);
```
This will fail if there is no active shell (e.g. application does not has focus). If there is no actie shell, it would be the best to use the dialog shell...

**Comment by lcaron** [comment]
Bug fixed in the next release if Nebula (nightly & stable) 
https://github.com/eclipse/nebula/pull/295
