### ISSUE TITLE
Inverted selection behaviour of SwitchButton

### ISSUE THREAD

**Issue by laeubi** [EclipseNebula/nebula#300]
The description [on the example page](https://wiki.eclipse.org/Nebula_SwitchButton) says:

> A switch button is a different graphic representation of a checkbox button.

but one need to call SwitchButton.setSelection(true) to have a button that is off...  that's not very intuitive and the opposite what a checkbox behaves...

**Comment by laeubi** [comment]
Another issue is, that when one calls SwitchButton.setSelection(...) one also need to trigger a redraw manually. This is a problem for every setter but becomes most prominent here. e.g. if the button can be switched on/of by a shortcut.

**Comment by laeubi** [comment]
Another observation:
When the event is fired because the user clicks on the button it returns the "previous" state that reverses the logic again and it seems "right" as a first place.

E.g. button is OFF, user clicks on the button.
If I print the button state from the click handler I call getSelection() the result is 'true', if I sometimes later call getSelection() (without any changes) the result is false.

This should be changed in the following way:

- if the button is in the off state getSelection() should return false
- if the button is in the on state getSelection() should return true
- if I call setSelection(false) the button should be showing "Off" afterwards
- if I call setSelection(true) the button should be showing "On" afterwards
- if SelectionListener() {...}.widgetSelected(SelectionEvent) is called it return the already changed value, eg. button was ON then the call to getSelection() should be false.

**Comment by wimjongman** [comment]
Thanks for reporting, Christopher. I think these are valid complaints. Are you able to supply a patch?

**Comment by lcaron** [comment]
Hi Christoph,

I'll work on this topic this week

Laurent

**Comment by lcaron** [comment]
> but one need to call SwitchButton.setSelection(true) to have a button that is off... that's not very intuitive and the opposite what a checkbox behaves...

You're totally right this is not user-friendly nor logical. This problem is fixed

> Another issue is, that when one calls SwitchButton.setSelection(...) one also need to trigger a redraw manually

Problem fixed fo all setters

> When the event is fired because the user clicks on the button it returns the "previous" state that reverses the logic again and it seems "right" as a first place.

This problem has been fixed too

**Comment by lcaron** [comment]
Bug fixed with PR https://github.com/eclipse/nebula/pull/302

**Comment by laeubi** [comment]
Many thanks for the fix!
