### ISSUE TITLE
Disabled TableCombo does not looks "disabled" enought

### ISSUE THREAD

**Issue by laeubi** [EclipseNebula/nebula#309]
If one disables a TableCombo the arrow is grayed out, but the border + text background remains the same and the text stays black.

It would be better for the user if the control is more visually "disabled", eg using SWT.COLOR_WIDGET_DISABLED_FOREGROUND, a different border color and so on.

**Comment by lcaron** [comment]
Look has been changed in Nebula 2.5.0, thanks for reporting
