### ISSUE TITLE
If TableCombo is opened the first time after input change it is too small

### ISSUE THREAD

**Issue by laeubi** [EclipseNebula/nebula#310]
1. Create a TableCombo and set it to disabled
2. set one item to it
4. set two items and enable it
5. open it -> appears to small (with scrollbars)
6. open it again --> looks fine

**Comment by lcaron** [comment]
Christoph,

Can you please post a snippet and a screenshot ?

I tried with the following snippet and I could not reproduce the problem : 


```
TableCombo tc = new TableCombo(group, SWT.BORDER | SWT.READ_ONLY);
tc.setLayoutData(new GridData(125, SWT.DEFAULT));
tc.setEnabled(false);
TableItem ti1 = new TableItem(tc.getTable(), SWT.NONE);
ti1.setText("One");

TableItem ti2 = new TableItem(tc.getTable(), SWT.NONE);
ti2.setText("Two");

TableItem ti3 = new TableItem(tc.getTable(), SWT.NONE);
ti3.setText("Three");
tc.setEnabled(true);
```

**Comment by lcaron** [comment]
Hi Christoph

Any news about this bug ? Can you please provide a snippet that reproduces the problem ?

Cheers,

Laurent

**Comment by laeubi** [comment]
Have you tested it under windows or Linux? I have seen this under Linux GTK so maybe a GTK specific problem?
I don't have a standalone snippet yet but can provide you with a screenshot how it looks like.

Opened fist time:
![grafik](https://user-images.githubusercontent.com/1331477/120759993-e6abc780-c513-11eb-9d7a-dda6b53f8802.png)

Close and open again:
![grafik](https://user-images.githubusercontent.com/1331477/120760189-22df2800-c514-11eb-8e6e-b07fe23e8616.png)

That is the code for construction:
```
TableComboViewer comboViewer = new TableComboViewer(composite, SWT.SINGLE | SWT.H_SCROLL | SWT.V_SCROLL | SWT.BORDER | SWT.READ_ONLY);
comboViewer.getTableCombo().setShowTableHeader(true);
comboViewer.getTableCombo().defineColumns(new String[]{"MF", "Matches", "Comparision"});
comboViewer.getTableCombo().setDisplayColumnIndex(2);
comboViewer.setContentProvider(ArrayContentProvider.getInstance());
comboViewer.setLabelProvider(new ComboLabelProvider());
comboViewer.getControl().setEnabled(false);
```

Then if an event is received we update the combo in the following way:
```
List<V> list = newValue.getResult();
V result = list.get(0);
comboViewer.setInput(list);
comboViewer.setSelection(new StructuredSelection(result));
comboViewer.getControl().setEnabled(list.size() > 1);
```

**Comment by lcaron** [comment]
Christoph,

I (hardly) reproduced the problem and fix it. Could cou try and check if my fix works with your example ?
