### ISSUE TITLE
TableCombo Readonly shows text selected all the time

### ISSUE THREAD

**Issue by laeubi** [EclipseNebula/nebula#311]
I have a TableCombo and set it to readonly, now the text is always  painted "selected" when I choose a value from the drop down.

**Comment by lcaron** [comment]
Christoph, 

I'm currently working on a huge Windowbuilder bug, but I'll work on TableCombo subjects next week

**Comment by laeubi** [comment]
No problem, I'm just dropping things here that came into my mind so I don't loose it, no need to worry.

**Comment by wimjongman** [comment]
Please supply a patch, Cristoph. We are a bit understaffed.

**Comment by lcaron** [comment]
Bug fixed in Nebula 2.5.0 

Thank you for reporting
