### ISSUE TITLE
PreferenceWindow flickers if opened

### ISSUE THREAD

**Issue by vogella** [EclipseNebula/nebula#313]
The 	SWTGraphicUtil.centerShell(shell); centeres the shell, after opening it hence a smaller flickering is seen.
Maybe center it before opening i?

In PreferenceWindow.java:

	 * Open the shell
	 */
	private void openShell() {
		shell.pack();
		shell.open();
		SWTGraphicUtil.centerShell(shell);

		while (!shell.isDisposed()) {
			if (!shell.getDisplay().readAndDispatch()) {
				shell.getDisplay().sleep();
			}
		}

	}

	/**

**Comment by wimjongman** [comment]
Looks like a small change. Can you supply a patch?

**Comment by lcaron** [comment]
Bug fixed in Nebula 2.5.0, thank you for reporting (and the hint ;) )
