### ISSUE TITLE
PrintPreview display blank page

### ISSUE THREAD

**Issue by ikus060** [EclipseNebula/nebula#314]
I have an issue with the PrintPreview. On one specific computer, the preview is always blank. I've tried to run the Snippet7 and Snippet3 and the preview is always blank. Trying the same snippet on another computer is working perfectly fine.

Was this problem ever reported and how to debug / fix this problem.

I'm using v2.1.0.202011020719, on windows.

![Screenshot from 2021-03-31 10-49-15](https://user-images.githubusercontent.com/921251/113165730-27cfe480-9210-11eb-89ae-cb5006bd3b99.png)

Take note, Snippet2 that uses PrintViewer is working fine.

**Comment by wimjongman** [comment]
Patrick, is there anything in the console? Why are the icon texts showing the file names?

**Comment by ikus060** [comment]
@wimjongman For my test, I've change the button creation to display test instead of image to simplify the execution.
I don't see anything getting send to the console.
BTW, when I'm printing to a real printer, the document get printed.

**Comment by lcaron** [comment]
Bonjour Patrick

Can you specify which JDK are you using ?

**Comment by ikus060** [comment]
Here the JVM version: 1.8.0u201

![image](https://user-images.githubusercontent.com/921251/114404753-ff32dd80-9b73-11eb-8653-cd53a6d76a12.png)

I don't think it's related to the JVM version. I could test on another computer with the same version...

**Comment by ikus060** [comment]
Anything special I can do to debug this ? I'm willing to test various thing but I also need some guidance. :D

**Comment by wimjongman** [comment]
Patrik, we are as clueless as you. There is no logging and it works on of your machines and not on one specific machine. It is very hard to debug.

I see this icon in your toolbar 
![image](https://user-images.githubusercontent.com/180969/115563346-b7b8f980-a2b7-11eb-8f07-0007ff785911.png)

What is it?

**Comment by ikus060** [comment]
@wimjongman This icon is the software I'm trying to debug. Since I cannot install a IDE on the computer, I've pre-compile the Snippet into the software it self to debug :) That was a quick solution to check if it's related to the software or if it was related to Nebula Paperclips.

Related to logs, Anything special I need to to do to enable Paperclips logging ?

And what is the difference between Snippet2 and Snippet7 ?
Can I tweak PrintPreview some how ?

**Comment by wimjongman** [comment]
What happens when you run the snippet normally from the IDE? What happens if you resize/minimize/maximize the window?

**Comment by wimjongman** [comment]
Related to logs: You have to look in the source for that. We are both looking at the same. 😉

**Comment by wimjongman** [comment]
When I run the snippets from the IDE I also see blank pages. However, when I print, the data is visible.

**Comment by ikus060** [comment]
So you are able to reproduce the problem. It's good news!

On a development machine, I can't. Now I'm wondering why. So I suspect the problem has an environmental source.

**Comment by ikus060** [comment]
What version of Java are you running ?

**Comment by wimjongman** [comment]
I think maybe it is the SWT version. What are the differences between the SWT versions on your machine?

**Comment by ikus060** [comment]
Hum, I have the same version on both computer: where the preview is blank and where the preview is working.

org.eclipse.swt.win32.win32.x86_64-3.115.0
org.eclipse.nebula.paperclips.widgets-2.1.0.202011020719
org.eclipse.nebula.paperclips.core-2.1.0.202011020719

I've also tried with:
org.eclipse.nebula.paperclips.widgets-2.0.0.201304181950
org.eclipse.nebula.paperclips.core-2.0.0.201304181950

**Comment by lcaron** [comment]
Hi Patrik,

Any news about this problem ?

**Comment by lcaron** [comment]
Hi Patrik,

Any news about this problem ?

**Comment by ikus060** [comment]
Didn't get back any complains from my users. Closing this.
