### ISSUE TITLE
DualList.select(int) do not work as exspected

### ISSUE THREAD

**Issue by laeubi** [EclipseNebula/nebula#331]
If I call `DualList.select(int)` the item is present in both lists

**Comment by laeubi** [comment]
I think a call to `items.remove(item)`' is missing here...

**Comment by wimjongman** [comment]
Christoph, if you make a couple of quality patches, I am happy to nominate you as a committer.

**Comment by laeubi** [comment]
@wimjongman I'll try to prepare some patches but atm I'm a bit busy with daily work and can only supply some feedback so I don't forget the issues encountered :-)

**Comment by wimjongman** [comment]
Thanks, Christoph.
