### ISSUE TITLE
Possibility to filter CTreeCombo  

### ISSUE THREAD

**Issue by ganubyn** [EclipseNebula/nebula#334]
Hello All,

We are planning to use CTreeCombo(package :org.eclipse.nebula.widgets.ctreecombo.CTreeCombo). Is there any filter option available to to filter the tree content.
In the provided example I didn't see this use case. 
Is it possible ? If it is possible can you share the example ?

**Comment by lcaron** [comment]
Hi
What do you mean by "filtering" ? Display only elements that match a given pattern ?

Laurent

**Comment by ganubyn** [comment]
Yes .  For example when we type words and  element matching elements shown.

**Comment by lcaron** [comment]
Now, when the CTreeCombo is not read-only, the tree is filtered : when ones clicks on the arrow, the tree contais only entries that match the text typed by the user.
