### ISSUE TITLE
[RichText] Support render image in RichText

### ISSUE THREAD

**Issue by lcaron** [EclipseNebula/nebula#344]
Copy of https://bugs.eclipse.org/bugs/show_bug.cgi?id=511111

Render images from local resources and external resources should be supported. External protocols such as http, https, ftp should be supported.

**Comment by x21L** [comment]
Are there any updates on image support?

**Comment by wimjongman** [comment]
We did not have time. Can you give it a shot?

**Comment by x21L** [comment]
Yes definitely

**Comment by lcaron** [comment]
Thank you, feel free to ask if you need help

**Comment by lcaron** [comment]
@x21L Any news about this issue ?

**Comment by x21L** [comment]
Yes I created a PR
see: https://github.com/eclipse/nebula/pull/484

**Comment by jmauersberger** [comment]
@lcaron IMHO the image support never made it into the master branch, am I right? I checked the code and do not see any change in the renderer class. Could you please double check? @x21L what do you think?

**Comment by fipro78** [comment]
AFAIK there is no code taken over to the main branch with regards to image rendering with the rich text viewer / editor. IIRC the reason is that the PR never reached an acceptable state. For example only the simplest use case of rendering a single image was handled, but the more complex use cases like alignment with the text etc were not considered.

**Comment by jmauersberger** [comment]
I thought so, thanks @fipro78 for confirmation. So ... this issue should be reopened again?

**Comment by fipro78** [comment]
It depends. Is there someone really interested in the topic and willing to contribute? Or do you just want to have a ticket open as some sort of backlog that shows what is not supported and maybe someone in the future might work on?

**Comment by jmauersberger** [comment]
I tend to the later, but I am also aware of the arguments against keeping tickets open forever. In any case,  the ticket should be maybe closed "wont fix" and not "closed complete" then. That was what irritated me in the first place.

**Comment by lcaron** [comment]
Hi Jan

My bad, you're totally right. The status "complete" is not relevant. I won't make the same mistake for future issues.

Thank you for your feedback

Laurent
