### ISSUE TITLE
Add Bundle-License Header to Nebula bundles

### ISSUE THREAD

**Issue by laeubi** [EclipseNebula/nebula#357]
Bundle-License` is a [standard OSGi Header](http://docs.osgi.org/reference/bundle-headers.html), for better compatibility we should add one to each published bundle.

My idea would be to add a [license to the pom](https://maven.apache.org/pom.html#Licenses) this should then be automatically be translated by tycho to the appropriate header.

As far as I know, there is currently no such feature in tycho, so this ticket could act as a starting-point to add such feature to tycho.

**Comment by lcaron** [comment]
Issue closed, thanks @laeubi & @wimjongman
