### ISSUE TITLE
Launcher schould be more flexible

### ISSUE THREAD

**Issue by laeubi** [EclipseNebula/nebula#359]
currently the launcher is a bit limited/fixed:

- columns are always item.size() / 2
- background is always "white"
- the size of an item is hard coded
- selection always happen on double click

so it would be good if

- items/column could be configured
- the background color can be changed
- it would be possible to configure a custom item size (or even better would adjust to the largest item)
- it would be possible to choose for example a "fast-selection-mode" where the action takes place on single click

**Comment by lcaron** [comment]
Interesting idea, i'll work on this for Nebula 2.6.0

**Comment by lcaron** [comment]
It is Christmas @laeubi ;)

You can now 
a) change the background color of selected & unselected items
b) Choose a fast selection mode
c) Change the font
d) Change the number of columns

And the size of each "block" is computed automatically (based on the largest/highest item).

Please have a look at : https://github.com/eclipse/nebula/blob/master/widgets/opal/launcher/org.eclipse.nebula.widgets.opal.launcher.snippets/src/org/eclipse/nebula/widgets/opal/launcher/snippets/LauncherSnippetAdvanced.java

**Comment by laeubi** [comment]
Great this looks very promising! :+1:

**Comment by lcaron** [comment]
@wimjongman why did you reopened this issue please ?

**Comment by wimjongman** [comment]
I don't know. I closed it again.
