### ISSUE TITLE
eclipse nebula perspective

### ISSUE THREAD

**Issue by thomas-covenant** [EclipseNebula/nebula#361]
i used the nebula perspective to design a combobox table
how can i now use the java source code. could not find a copy / paste or drag it into the windowbuilder designer?

**Comment by wimjongman** [comment]
You can't. It does not have that functionality.

**Comment by wimjongman** [comment]
You can use the snippets to get examples. 

https://github.com/eclipse/nebula/tree/master/examples/org.eclipse.nebula.snippets/src/org/eclipse/nebula/snippets
