### ISSUE TITLE
How to change PTProperty color when the property changed? (to identify changes)

### ISSUE THREAD

**Issue by ghelle** [EclipseNebula/nebula#368]
I want to change the property color of a PropertyTable when a property is modified.
I am using PTPropertyChangeListener to get the new PTProperty value but i want to change th PTProperty color to show the modified property…
There is no no access to the widget / Item of the property…to change the color
What is the way for that ?

Thanks for your help

Guillaume Helle

**Comment by lcaron** [comment]
https://github.com/eclipse/nebula/pull/369

The PTProperty object contains now 3 methods to change the graphical aspect of the "display name" associated to the property: `changeFont()`, `changeBackgroundColor()` and `changeForegroundColor()`

The PropertyTable contains a new method `discardChanges()` that resets the values stored in the table.
