### ISSUE TITLE
check box in TableCombo to select multiple items 

### ISSUE THREAD

**Issue by vnairathira** [EclipseNebula/nebula#374]
Hello All,

Is it possible to add check box in TableCombo (org.eclipse.nebula.widgets.tablecombo.TableCombo) ?
We have a requirement where we can add check box in a combo dropdown and select multiple items. checked item should be added in text area with a comma separator 
Is there any example for it?

**Comment by lcaron** [comment]
Hi

It is not possible yet with TableCombo, but you can use the **Multichoice** widget : https://wiki.eclipse.org/Nebula_Multichoice

What do you think ?

**Comment by vnairathira** [comment]
This is a great suggestion. Filtering item is also possible with this?   (Type anything in text area and related items should be shown in the dropdown. This would be helpful if we set large data and user don't know what exactly they are looking for)

**Comment by lcaron** [comment]
Interesting proposal, but unfortunately the "multichoice" widget does not accept filtering, and in case of large data the pop up window may overflow. If one enhances the "Table combo" widget (with checkbox) he has to implement filtering (the text part the table combo is read only).

Fitting both requirements needs a brand new component I think.

Do you want to work on such component ?

**Comment by vnairathira** [comment]
Thankyou for the reply. right now "multichoice" widget meet our requirement.

**Comment by lcaron** [comment]
Great, thank you for your feedback
