### ISSUE TITLE
Add SWTTiles project to Nebula

### ISSUE THREAD

**Issue by lcaron** [EclipseNebula/nebula#381]
I got in touch with Fabian Prasser, the author of SWTTiles (https://github.com/prasser/swttiles), and he accepted to include his widget in Nebula 👍

**Comment by wimjongman** [comment]
Wow! That is a really nice addition. Thanks, @prasser and @lcaron

**Comment by prasser** [comment]
I'm very happy to have this widget included in Nebula! This is exciting!

**Comment by lcaron** [comment]
Tiles is now part of Nebula 👍 

Than you @prasser for your trust and this fantastic widget !

**Comment by prasser** [comment]
Great. I have to thank you, @lcaron and the Nebula team, for keeping this library maintained! Should you run into issues that I could help with, feel free to ping me!

**Comment by wimjongman** [comment]
Fabian, you are welcome to join us. We can use people that know how to push a pixel.
