### ISSUE TITLE
Gallery Tests fail on Mac

### ISSUE THREAD

**Issue by janiak-minova** [EclipseNebula/nebula#385]
I tried building the project on macOS Big Sur with `mvn clean verify`, but get the following error:

```
***WARNING: Display must be created on main thread due to Cocoa restrictions. Use vmarg -XstartOnFirstThread
An error has occurred. See the log file
```

**Comment by vogella** [comment]
I think pomless build does that automatically. Can you try to setup #384 ?

**Comment by vogella** [comment]
Tested with pomless builds and the same error. Will create an issue for Tycho.

**Comment by laeubi** [comment]
Please see https://stackoverflow.com/questions/46485846/java-xstartonfirstthread-command-line-options-unrecognized-in-linux-but-working

**Comment by laeubi** [comment]
-  https://github.com/eclipse/tycho/discussions/234

**Comment by lcaron** [comment]
@janiak-minova Any news about this bug ?

**Comment by lcaron** [comment]
@janiak-minova Any news about this bug ?

**Comment by janiak-minova** [comment]
I just tried to build the project again (macOS Monterey), but still get the same error during the gallery tests:

```
***WARNING: Display must be created on main thread due to Cocoa restrictions. Use vmarg -XstartOnFirstThread
```




> Please see https://stackoverflow.com/questions/46485846/java-xstartonfirstthread-command-line-options-unrecognized-in-linux-but-working

Following the advice in the first reply of this issue, I added a profile to the pom of `org.eclipse.nebula.widgets.gallery.tests`:
```
<profiles>
    <profile>
        <id>platform-mac</id>
        <activation>
            <os>
                <family>mac</family>
            </os>
        </activation>
        <build>
            <plugins>
                <plugin>
                    <groupId>org.eclipse.tycho</groupId>
                    <artifactId>tycho-surefire-plugin</artifactId>
                    <version>2.6.0</version>
                    <configuration>
                        <argLine>-XstartOnFirstThread</argLine>
                    </configuration>
                </plugin>
            </plugins>
        </build>
    </profile>
</profiles>
```

With this, the gallery tests were built successfully, but then the same error occurred in the oscilloscope tests.

**Comment by lcaron** [comment]
Thank you for your  feedback. I've received a brand new Mac at work, I will work on this.

**Comment by wimjongman** [comment]
No action on this item. If anyone feels the need to fix this for mac then PR's are welcome.

Closing for now.
