### ISSUE TITLE
Question: Update Java version?

### ISSUE THREAD

**Issue by vogella** [EclipseNebula/nebula#408]
I see that lots of widgets are still based on pre Java 11 versions. As platform and JFace moved a while ago to Java 11 and giving that Java 17 is the latest long term maintenance version, could we also start moving Nebula widgets to Java 11?

**Comment by vogella** [comment]
Also SWT moved to Java 11.

**Comment by vogella** [comment]
@wimjongman WDYT`?

**Comment by wimjongman** [comment]
Yes, we should move everything to Java 11.

**Comment by lcaron** [comment]
When you talk about migration, do you think about simply changing pom.xml, manifest.mf, etc. or also use modules ?
(I never understood why Java team decided to create Jigsaw from scratch when OSGi works flawlessly)

**Comment by fipro78** [comment]
I would not do anything with regards to modules despite adding the Automatic-ModuleName to the manifest (if it is not there already).

**Comment by lcaron** [comment]
Postponed to 2.7.0. I'll work on this after the release of Nebula 2.6.0 (February 1st)

**Comment by lcaron** [comment]
I'll work on this topic this week

**Comment by lcaron** [comment]
We are close from the release date, so the migration is planned for 2.8.0 (long and tricky work :) )

**Comment by lcaron** [comment]
Nebula needs now a JDK 11 to run ;)
