### ISSUE TITLE
ProgressCircle requires a specific SWT version

### ISSUE THREAD

**Issue by wimjongman** [EclipseNebula/nebula#41]
https://github.com/eclipse/nebula/blob/5209a3de9803757807d7a75c478607fbac4bd5c4/widgets/progresscircle/org.eclipse.nebula.widgets.progresscircle/META-INF/MANIFEST.MF#L9

Is this really needed? Also, why do you re-export SWT?

**Comment by lcaron** [comment]
Problem fixed

**Comment by wimjongman** [comment]
Issue tracker reference: https://bugs.eclipse.org/bugs/show_bug.cgi?id=544474
