### ISSUE TITLE
Hard-coded margins in preference window

### ISSUE THREAD

**Issue by vogella** [EclipseNebula/nebula#413]
Currently the Apply and Close buttons at the end of the dialog do not have margins as the shell hard-code this to zero. This looks IMHO not in line with other SWT widgets.

![image](https://user-images.githubusercontent.com/139910/141089828-203ce671-56f7-4554-98cd-a7853409828c.png)

I think it looks better without hard-coded marings to zero:

![image](https://user-images.githubusercontent.com/139910/141090040-21493d67-1443-424f-9d57-968f75d504f7.png)

PR coming soon.

**Comment by vogella** [comment]
![image](https://user-images.githubusercontent.com/139910/141090115-c93f429d-8500-442d-affa-e9cfdb9d010a.png)

**Comment by vogella** [comment]
Noted that this affects also the button container. PR needs more work...

**Comment by vogella** [comment]
![image](https://user-images.githubusercontent.com/139910/141108575-8e5eb7ce-225b-40a5-b978-7225f52ca9ed.png)

Background highlighted in the screenshot. This one looks IMHO better. PR will be updated.

**Comment by lcaron** [comment]
Postponed to 2.7.0

**Comment by lcaron** [comment]
Fixed and verified in V3.1.1 (thanks to @vogella )

**Comment by vogella** [comment]
Thanks to you @lcaron
