### ISSUE TITLE
TextAssist appears in the background

### ISSUE THREAD

**Issue by Bauer-David** [EclipseNebula/nebula#419]
I noticed that the popup of TextAssist is sometimes displayed in the background. The style is set to SWT.ON_TOP. This error occurs very sporadically and only under windows.

![Popup in the background](https://user-images.githubusercontent.com/20420949/140722328-a586ae4b-df5b-4758-9225-9072031de791.png)

In the picture above you can see how the popup is displayed in the background. If it helps, here is my line of code where I create the Text Assist.

`TextAssist text = new TextAssist(composite, SWT.BORDER, contentProvider);`

**Comment by wimjongman** [comment]
Thanks, David. Can you supply a patch?

**Comment by Bauer-David** [comment]
No, sorry. I was hoping that you might come to a solution. I'm still trying to solve it, but unfortunately I'm at a dead end.

**Comment by wimjongman** [comment]
Before popup.setVisible(true) please set popup.setActive()

This will bring the popup to the foreground before it is made visible. Please try with this setting and if it works you can supply a pull request.

**Comment by wimjongman** [comment]
That has glitches on windows. Try this block instead:

			if (!popup.isVisible()) {
				popup.setActive();
				popup.setVisible(true);
			}

**Comment by Bauer-David** [comment]
Thank you. I will test your solution and give you feedback when I see results. It might take a while because the error is very sporadic. I will create a pull request if it works.

**Comment by lcaron** [comment]
@Bauer-David Any news about this bug please ?

**Comment by Bauer-David** [comment]
Sorry for the late reply. We have tested your solution but it was not successful. If we find another solution I will post it here

**Comment by lcaron** [comment]
Ok, feel free to ask help !

**Comment by Bauer-David** [comment]
We continued testing and tried a few solutions, but nothing fixed the error. We also noticed that the error occurs almost exclusively on native Windows. For example, it does not occur on Parallels. If you have any further solutions or help here, we would be very grateful. 

If it helps you, here is some more information about our application:

Used Java Version: Amazon Corretto 11 [11.0.6]
Used Framework: e4 RCP

Code of our time field:



		TextAssistContentProvider contentProvider = new TextAssistContentProvider() {
			@Override
			public List<String> getContent(String entry) {
				ArrayList<String> result = new ArrayList<>();
				Instant time = TimeUtil.getTime(entry);
				if (time == null && !entry.isEmpty()) {
					result.add(translationService.translate("@msg.ErrorConverting", null));
				} else {
					Preferences preferences = 
                                    InstanceScope.INSTANCE.getNode(ApplicationPreferences.PREFERENCES_NODE);
					String timeUtil = (String) InstancePreferenceAccessor.getValue(preferences,            
                                    ApplicationPreferences.TIME_UTIL, DisplayType.TIME_UTIL, "",
							locale);
					result.add(TimeUtil.getTimeString(time, locale, timeUtil));
					field.setValue(new Value(time), true);
				}
				return result;
			}

		};

            TextAssist text = new TextAssist(composite, SWT.BORDER, contentProvider);
		LocalDateTime date = LocalDateTime.of(LocalDate.of(2000, 01, 01), LocalTime.of(11, 59));
		text.setMessage(TimeUtil.getTimeString(date.toInstant(ZoneOffset.UTC), locale, timeUtil));
		text.setNumberOfLines(1);
		text.setData(TRANSLATE_LOCALE, locale);
		text.addFocusListener(new FocusAdapter() {
			@Override
			public void focusGained(FocusEvent e) {
				text.selectAll();
			}

			@Override
			public void focusLost(FocusEvent e) {
				if (text.getText().isBlank()) {
					field.setValue(null, true);
				}
			}
		});

If you need more information feel free to ask. Here is also a link to our GitHub repository [WFC RCP](https://github.com/minova-afis/aero.minova.rcp).

**Comment by lcaron** [comment]
Thank you for this detailled feedback. I'll try to investigate the next days.

**Comment by wis36** [comment]
> That has glitches on windows. Try this block instead:
> 
> ```
> 		if (!popup.isVisible()) {
> 			popup.setActive();
> 			popup.setVisible(true);
> 		}
> ```

This will actually do nothing, because `setActive()` returns when the Shell is not visible.

**Comment by wis36** [comment]
I tested some days on native Windows. I don't know why this happens, Windows 10 also sends other shells to background.

But I found something that helps. I'll try a pull request.

**Comment by lcaron** [comment]
I'll have a look tonight and make some tests. I'll keep you informed.

**Comment by lcaron** [comment]
Hi Stefan,

Thank you for your patch. I tested it and it is ok for me.
In order to merge your fix in Nebula you have to sign the Eclipse Contributor Agreement (https://www.eclipse.org/legal/ECA.php) with the email you used in your commit.

Feel free to ask !

**Comment by wis36** [comment]
Would it be better to change the commit to my other email? Changing the email of my Eclipse Account seems not that simple.

**Comment by lcaron** [comment]
Hi Stephan,

Sure, you can amend the commit. The most important consists of commiting with an email associated to the ECA.

Laurent

**Comment by wis36** [comment]
Amend after push did not solve the problem - now both email addresses are required.
I'll try another branch.

**Comment by lcaron** [comment]
The PR has been merged.

@Bauer-David Can you please tried with the latest snapshot ?

**Comment by Bauer-David** [comment]
Stefan and I are in the same company. We tested it and it works for us. From my site the issue can be closed. Thank you for your help.

**Comment by lcaron** [comment]
Thank you for your contribution !
