### ISSUE TITLE
[RichText] Can you add config to disable URL autolinking?

### ISSUE THREAD

**Issue by olivergardiner** [EclipseNebula/nebula#439]
I'm currently using RichText to implement a custom comment editor for Papyrus but the auto URL linking feature of most browsers is problematic as it formats any text with (e.g.) an "@". I have a local fork that adds the line:

document.execCommand("AutoUrlDetect", false, false);

to the start of the <script> section in template.html which does the trick.

It would be great if this could be a configurable (ideally default) behaviour.

Thanks

**Comment by lcaron** [comment]
@fipro78 can you handle this bug or do you want me to work on it ?

What is your opinion ?

**Comment by fipro78** [comment]
Well, my first opinion is ... if someone is able to fork and change things he is surely also able to contribute! ;-)

Second opinion, not sure if document.execCommand() is the right way, or if it would be better to add a BrowserFunction to dynamically be able to change the configuration. I can have a look if the reporter is not willing to contribute.

**Comment by olivergardiner** [comment]
This is my modified template file: 

https://github.com/olivergardiner/palladium/blob/master/org.eclipse.swt.nebula-root/widgets/richtext/org.eclipse.nebula.widgets.richtext/src/org/eclipse/nebula/widgets/richtext/resources/template.html

The added line is line 41

There's a difference between getting maven to build and modifying a simple HTML file and delving into the nebula code but happy to look into it if that would help.

**Comment by fipro78** [comment]
OK, looking into this issue I have collected some information:

1. It is an IE only issue as far as I can tell. It is also known in the CKEditor community https://dev.ckeditor.com/ticket/6307
2. There is actually no need to fork and modify the template.html file. The `RichTextEditor` provides an API to execute Javascript. So you can enable and disable that feature dynamically already.
3. The only issue with disabling the feature on startup is the timing. As the `Browser` is not yet finished with loading when you create it via constructor, it needs to be executed in a `ProgressListener`. The `Browser` is not directly accessible via the `RichTextEditor`, but you can get to it via the `RichTextEditorConfiguration` like this:

        editor.getEditorConfiguration().getBrowser().addProgressListener(new ProgressListener() {
        
            @Override
            public void completed(ProgressEvent event) {
                editor.executeJavascript("document.execCommand('AutoUrlDetect', false, false);");
            }
	
            @Override
            public void changed(ProgressEvent event) {
            }
        });

I will check if I can make it more comfortable for users via a configuration attribute. But definitely it is not necessary to fork and modify the template.html for this. ;-)
