### ISSUE TITLE
Gallery Widget, virtual mode crashed if using swt 4.9 

### ISSUE THREAD

**Issue by ivanooi** [EclipseNebula/nebula#444]
Hi all,

Gallery Widget virtual mode crashed when using SWT 4.9 on Mac 
this is the error : 

 java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.internal.cocoa.NSGraphicsContext.graphicsPort()" because "graphicsContext" is null
	at org.eclipse.swt.widgets.Control.internal_new_GC(Control.java:2180)
	at org.eclipse.swt.graphics.GC.<init>(GC.java:177)
	at org.eclipse.nebula.widgets.gallery.DefaultGalleryGroupRenderer.pre(DefaultGalleryGroupRenderer.java:574)
	at org.eclipse.nebula.widgets.gallery.DefaultGalleryGroupRenderer.preLayout(DefaultGalleryGroupRenderer.java:560)
	at org.eclipse.nebula.widgets.gallery.Gallery.calculateSize(Gallery.java:1560)
	at org.eclipse.nebula.widgets.gallery.Gallery.updateStructuralValues(Gallery.java:1525)
	at org.eclipse.nebula.widgets.gallery.Gallery.setItemCount(Gallery.java:259)

Best Regards,
Ivan

**Comment by wimjongman** [comment]
Please try the latest version SWT 4.22

https://download.eclipse.org/eclipse/downloads/drops4/R-4.22-202111241800/

**Comment by ivanooi** [comment]
but i need SWT 4.9 which is last 32bit.... it is ok with SWT 17

**Comment by lcaron** [comment]
Hi
What version of OSX do you use ? SWT had problems with Big Sur

**Comment by wimjongman** [comment]
It looks like this bug was solved in SWT. It was pushed also to 4_6 maintenance but I don't know how to build this from source.

It does not look like a Nebula issue.

https://bugs.eclipse.org/bugs/show_bug.cgi?id=547399

**Comment by ivanooi** [comment]
> Hi What version of OSX do you use ? SWT had problems with Big Sur

Hi, I'm using Mac OS 10.15

Thanks

**Comment by lcaron** [comment]
This SWT bug (look at the bugzilla issue 547 399) has been fixed for version 4.12 and backported to 4.6,4.7 and 4.8 (but not 4.9).
Can you try with 4.8 : https://archive.eclipse.org/eclipse/downloads/drops4/R-4.8-201806110500/download.php?dropFile=swt-4.8-cocoa-macosx-x86_64.zip

I confirm that this is not a Nebula bug but a SWT one

**Comment by lcaron** [comment]
Close this issue

**Comment by ivanooi** [comment]
> This SWT bug (look at the bugzilla issue 547 399) has been fixed for version 4.12 and backported to 4.6,4.7 and 4.8 (but not 4.9). Can you try with 4.8 : https://archive.eclipse.org/eclipse/downloads/drops4/R-4.8-201806110500/download.php?dropFile=swt-4.8-cocoa-macosx-x86_64.zip
> 
> I confirm that this is not a Nebula bug but a SWT one

Hi, sorry for my late reply. Yes, you;re right. no issues with 4.8 except 4.9 thanks again
