### ISSUE TITLE
Bug:-MultiChoice Widget adding Select all as an entry 

### ISSUE THREAD

**Issue by vnairathira** [EclipseNebula/nebula#454]
We are using org.eclipse.nebula.widgets.opal.multichoice.MultiChoice widget and We are using "Select All" functionality to select all or deselect all the checkboxes using setSelectionListener(new MultiChoiceSelectionListener<Country>(mcSL). But  "Select All" is also added as an entry in text box. When I save this data to database it is an invalid data. 
please refer attached image. could you please provide a solution to avoid select all as an entry to textbox
![bug_MultiChoice](https://user-images.githubusercontent.com/44398747/158960173-113eafe8-8ce7-47e0-899e-55a1bbb5b176.PNG)
.

**Comment by wimjongman** [comment]
Thanks for reporting @vnairathira. Are you able to supply a patch for this?

**Comment by lcaron** [comment]
Thank you for your report. It is not possible to implement a "select all" function without modifiying the code.
We can help you if you decide to provide a patch. Feel free to ask !

**Comment by lcaron** [comment]
Once the `Multichoice `object is created, you can display the "Select All/Deselect All" links by calling the method `setShowSelectUnselectAll(true)`

![image](https://user-images.githubusercontent.com/1170014/177013130-cdac43f2-d38e-4402-99d2-5979774abc86.png)

**Comment by vnairathira** [comment]
Thankyou for the update. It really helps our requirement. 
But when I click on "Select All/Deselect All" list is not updating on Text field. setLabel() needs to be added in selectAllLink.addListener() and deselectAllLink.addListener() 

selectAllLink.addListener(SWT.Selection, e -> {
				changeButtonState(true);
				setLabel(); 
			});
deselectAllLink.addListener(SWT.Selection, e -> {
				changeButtonState(false);
				setLabel();
			});

**Comment by lcaron** [comment]
You're right, I'm gonna fix it tonight and prepare a minor release

**Comment by lcaron** [comment]
Bug fixed in Nebula 2.7.1, which is (just) released.
