### ISSUE TITLE
FontAwesome does not work on Linux

### ISSUE THREAD

**Issue by vogella** [EclipseNebula/nebula#455]
The example code for the FontAwesome widget does not render well.

Label text = new Label(parent, SWT.NONE);
text.setFont(FontAwesome.getFont());
text.setText(FontAwesome.code);

Look like the following:

![image](https://user-images.githubusercontent.com/139910/160854726-60c36b18-7d4e-4829-ba08-1caee3ec1e23.png)

**Comment by lcaron** [comment]
@vogella what OS & Graphic Toolkit do you use please ?

**Comment by lcaron** [comment]
@vogella what OS & Graphic Toolkit do you use please ?

**Comment by vogella** [comment]
Sorry for the late reply. I use latest official Ubuntu release, most of the time with Wayland

**Comment by lcaron** [comment]
No problem, I'll have a look.

**Comment by wimjongman** [comment]
Could this be related with #498

**Comment by lcaron** [comment]
@vogella can you please try ? Thank you

**Comment by merks** [comment]
I'll close it and assume it works.  It can be reopened if that's not the case.
