### ISSUE TITLE
Update plugins version

### ISSUE THREAD

**Issue by lcaron** [EclipseNebula/nebula#461]
Currently version number are completly messy (https://download.eclipse.org/nebula/releases/2.5.0/plugins/).
I propose to move all plugins to version 2.6.0.qualifier.

**Comment by lcaron** [comment]
Any concern @wimjongman @fipro78 @vogella ?

**Comment by fipro78** [comment]
Yes I have concerns. Actually the plugins use semantic versioning. And each plugin/widget has its own version. The nebula version itself is the version of the parent, means not every plugin/widget is updated for a release. I think that approach is perfectly valid and should be kept.

**Comment by wimjongman** [comment]
I agree with Dirk. Versions should be updated when changes are made to a widget according to sematic versioning.

**Comment by laeubi** [comment]
> Yes I have concerns. Actually the plugins use semantic versioning. And each plugin/widget has its own version. The nebula version itself is the version of the parent, means not every plugin/widget is updated for a release. I think that approach is perfectly valid and should be kept.

+1

**Comment by lcaron** [comment]
Thank you for you feedback, I'll close this bug. Anyway, we should (and I include myself) more rigorous when a bug is fixed, and increase the plugin version.

**Comment by vogella** [comment]
@lcaron, maybe we should add baseline support? This way GH build action will tell you if you need a version increase.

See https://github.com/eclipse/gef-classic/blob/master/pom.xml#L19 and https://github.com/eclipse/gef-classic/blob/master/pom.xml#L185 for the way @azoitl added it for GEF classic.

**Comment by laeubi** [comment]
There is also an outstanding issue in Tycho to add the BND OSGI baseline support, but has not gotten much interest fro now, so if one sees a use case let us know: 
- https://github.com/eclipse/tycho/issues/115

**Comment by lcaron** [comment]
Thank you very much for your feedbacks. My experience with RCP app is the product of our company, so all plugins have the same version number (all plugins are elements of a whole product).

Cheers,
Laurent

**Comment by wimjongman** [comment]
Right. When single bundles are not important then this is fine. We do the same actually. We update all plugins during the build from a marker 88.88.88 to the version number we are building for. It is not correct from a semantic versioning standpoint but it works very well.

In case of having to deploy single bundles, as we do in Nebula, then we have to use semantic versioning.

Cheers, Wim
