### ISSUE TITLE
 XViewer customizations not saving filter

### ISSUE THREAD

**Issue by wimjongman** [EclipseNebula/nebula#466]

**Comment by wimjongman** [comment]
@dondunne please file issues in the future so that we have a milestone list of changes.

**Comment by dondunne** [comment]
How does one "file issues"?

Don

**Comment by wimjongman** [comment]
![image](https://user-images.githubusercontent.com/180969/169232528-9e93323e-b537-4396-8b4f-2940af718681.png)
