### ISSUE TITLE
Show selection of Mutichoice widget displays empty shell when entries are selected through "select All" option

### ISSUE THREAD

**Issue by kpvinutha** [EclipseNebula/nebula#485]
We are using org.eclipse.nebula.widgets.opal.multichoice.MultiChoice widget and We are using "Select All" functionality to select all or deselect all the checkboxes.With "Select All" ,getSelection() method return empty listn. But ,If I select individual entries one by one ,then getSelection() method is returning list of selected entries. 
please refer the attached image in which I selected entries with "select All" option and clicked on "show selection". It displays empty shell without any selected entries. could you please provide a solution to get selected entries even if we select via select all option.
![ShowSelection](https://user-images.githubusercontent.com/110931709/183904765-25056c0a-dfc0-4050-8564-b002f4a2b871.PNG)

**Comment by wimjongman** [comment]
Thanks for reporting. Are you able to supply a patch?

https://github.com/eclipse/nebula

**Comment by lcaron** [comment]
Hi @kpvinutha 

Thank you for reporting. This bug is fixed, please check the snapshot : https://download.eclipse.org/nebula/snapshot

If it is ok for you, I'll create a minor release (V2.7.2) next week (15th or 16th of August)

Please keep me informed.

**Comment by kpvinutha** [comment]
Hello @lcaron ,
Verified the snapshot. It perfectly suits our requirement. Please go ahead with the release.
Thank you for the quick fix.

**Comment by lcaron** [comment]
Fixed in Nebula 2.7.2

**Comment by lcaron** [comment]
Nebula 2.7.2 is now available
