### ISSUE TITLE
incubation update site should be fixed in a version...

### ISSUE THREAD

**Issue by opcoach** [EclipseNebula/nebula#497]
When we use incubation plugins from this update site : https://download.eclipse.org/nebula/incubation/snapshot and we refer to the p2 repository with the tpd editor the URL in target file will change every time the content of the snapshot site changes (ie : in the target file the release of feature is used and will change...). 

So it is absolutely not handy to have to recreate the target file each time the  incubation repository is regenerated. 

Would it be possible to have a fixed repository for incubation ?  

Or the projects that t are in incubation could now be moved in the nebula release ?

**Comment by wimjongman** [comment]
> Or the projects that t are in incubation could now be moved in the nebula release ?

This is the solution. We do not make incubation releases so there is no fixed repo.

**Comment by opcoach** [comment]
Hi Wim :) What is the criteria to let a project in incubation ? There are there for more than 2 years and should not be considered as incubated anymore right ?

**Comment by wimjongman** [comment]
All incubated widgets go there, and all widgets that don't have an active maintainer. Which widgets do you want to adopt? 😉

**Comment by opcoach** [comment]
We use those one : 

location "https://download.eclipse.org/nebula/incubation/snapshot/"
{
	org.eclipse.nebula.widgets.datechooser.feature.feature.group 
	org.eclipse.nebula.widgets.calendarcombo.feature.feature.group
	org.eclipse.nebula.widgets.formattedtext.feature.feature.group
}

**Comment by wimjongman** [comment]
Just for you, I made a latest incubation repository.

This one changes only with every release. We cannot provide a static incubation repo. 

https://download.eclipse.org/nebula/incubation/latest

**Comment by opcoach** [comment]
I come back with this issue... this is really not handy when we use the tpd editor to have a new location URL each time a new incubation is built and released... We have to re-generate the target file. 

We are using the pagination feature in the project, and we have only this line in the tpd file : 

location "https://download.eclipse.org/nebula/incubation/latest" {
	org.eclipse.nebula.widgets.pagination.feature.feature.group
}

I updated my target file from the tpd last week, and I got this location : 

```
   <location includeMode="planner" includeAllPlatforms="false" includeSource="true" includeConfigurePhase="false" type="InstallableUnit">
      <unit id="org.eclipse.nebula.widgets.pagination.feature.feature.group" version="1.0.0.202406291220"/>
      <repository location="https://download.eclipse.org/nebula/incubation/latest"/>
    </location>
```

Today, I have another version in  my target file : 

```
   <location includeMode="planner" includeAllPlatforms="false" includeSource="true" includeConfigurePhase="false" type="InstallableUnit">
      <unit id="org.eclipse.nebula.widgets.pagination.feature.feature.group" version="1.0.0.202411291049"/>
      <repository location="https://download.eclipse.org/nebula/incubation/latest"/>
    </location>

```

And the problem is that the old version has disappeared on the p2 repository.

These incubations widgets should either be considered as regular widgets or we should be able to get rid of the version.

**Comment by merks** [comment]
There's only a single update site  now that includes the incubation widgets

https://download.eclipse.org/nebula/updates/

It's structured as documented here:

https://eclipse.dev/justj/?page=tools

The site you are using just composes this site:

https://download.eclipse.org/nebula/updates/nightly/latest

Are the things you are using in this site?

https://download.eclipse.org/nebula/updates/release/3.1.1

Of course if you use a specific release site it will never change until you change the URL.

**Comment by opcoach** [comment]
Thank you Ed for these reminders.

 I only need the org.eclipse.nebula.widgets.pagination.feature.feature.group and if I look for it in the "Eclipse repository Search" dialog it is available here :  

![image](https://github.com/user-attachments/assets/33fb8226-31ed-4eb3-9fb2-7e12e6f8f3e8)

So I think that using this location : 

```
 location "https://download.eclipse.org/nebula/updates/milestone" {
	org.eclipse.nebula.widgets.pagination.feature.feature.group
}
```

it will be more 'stable' than using the incubation/latest. Right ?

**Comment by opcoach** [comment]
Another question : what is the condition to move 'Pagination' from incubation to release ? It is may be time to make the move ?

**Comment by merks** [comment]
Yes, milestone builds are less frequent.  What's not clear is your goal.  To get updates as soon as possible, less often, or only when you choose?

I think to get it out of incubation is only a matter of moving it from one feature to another.   But that's not my decision to make.

**Comment by opcoach** [comment]
> Yes, milestone builds are less frequent. What's not clear is your goal. To get updates as soon as possible, less often, or only when you choose?

Only when we choose them.  I changed it with milestones. I should probably include the tpd -> target generation in the pom build so as to be sure that new 'latest' component are correctly synchronized in the target file. I will check that. Thank you Ed.
