### ISSUE TITLE
Fontawesome do not work with multiple users.

### ISSUE THREAD

**Issue by riyueniao** [EclipseNebula/nebula#498]
Run the following code by two users at the same time, then the second user's run can not show the icon correctly.
```java
Button btn = new Button(parent, SWT.PUSH);
btn.setFont(FontAwesome.getFont());
btn.setText(FontAwesome.long_arrow_right);
```

Result on the second run.
![image](https://user-images.githubusercontent.com/41854481/203891044-1bf38f37-f779-4fe7-9329-a99605109390.png)

**Comment by wimjongman** [comment]
What do you mean by two users at the same time? Can you be more specific?

**Comment by riyueniao** [comment]
For example,  userA run the code and hold the UI. Then userB run the same code two.
OS: centos 7

**Comment by wimjongman** [comment]
I think I fixed this. Please try with the nightly build.

**Comment by wimjongman** [comment]
A snapshot build is available here https://download.eclipse.org/nebula/snapshot/
