### ISSUE TITLE
TableComboViewer dropdown not closed automatically on mouse click on the dialog area

### ISSUE THREAD

**Issue by ajaylamba-provar** [EclipseNebula/nebula#499]
Thr dropdown of TableCombo is not closed when clicking on empty space on the parent dialog.
The TableComboViewer uses TableCombo internally which handles the dropdown open and close action through org.eclipse.nebula.widgets.tablecombo.TableCombo.dropDown(boolean).

In the latest version 1.2.0 of tablecombo, the parent dialog remains activated when dropdown is opened. This in turn causes issues in closing the dropdown.

Note: The dropdown is closed when clicked on any control e.g. text, button etc.  because of respective event trigger. It also gets closed when the parent dialog moves out of focus.

Versions: 
org.eclipse.nebula.widgets.tablecombo - 1.2.0
org.eclipse.swt.win32.win32.x86_64 - 3.121.0
Eclipse version - 2022-09
JDK-11.0.16.9 (Amazon Corretto)
OS - Windows 10

**Comment by ajaylamba-provar** [comment]
One more thing I noticed is that when the dropDown is opened, the parent dialog box doesn't loose focus which means focusOut event is not triggered? While in older versions of eclipse/swt/nebula, the parent dialog is no more in focus and when we click again on the dialog, probably the focus event is triggered but not very sure about this.

**Comment by wimjongman** [comment]
Hey Ajay. Thanks for the analysis. Can you make a patch and provide it through a pull request?

Please see the [README](https://github.com/eclipse/nebula/#readme) on how to set up a development environment.

**Comment by ajaylamba-provar** [comment]
Hi @wimjongman, I think there is some misunderstanding here. I have not found the root cause yet. I have added my analysis just to help in understanding the issue.

**Comment by wimjongman** [comment]
Ah, ok. It looks like you are very much qualified to contribute. Just give it a try.

**Comment by ajaylamba-provar** [comment]
yes, I am trying to find the root cause. It's just that it is difficult to debug because of different events being triggered e.g. focusOut on moving the cursor to the debug window :D. Will give it another try and will add my analysis.

**Comment by wimjongman** [comment]
Yes, that is tricky. Maybe add some tracing in the events?

**Comment by wimjongman** [comment]
With tracing I mean some console printing.

**Comment by ajaylamba-provar** [comment]
This seems to be similar to the issue https://bugs.eclipse.org/bugs/show_bug.cgi?id=543226. @lcaron 

And it is occurring due to the changes done in https://github.com/eclipse/nebula/commit/e2295ddc18d4fd1e11d49de759faa314d292d874.
@mpscholz @wimjongman 

It is working fine if we revert the changes done in https://github.com/eclipse/nebula/commit/e2295ddc18d4fd1e11d49de759faa314d292d874

**Comment by ajaylamba-provar** [comment]
@mpscholz could you please suggest?

**Comment by mpscholz** [comment]
Hi Ajay,

Sorry, this escaped me due to the holidays...

It's been quite a time ago, but if I remember well, the commit fixed a
serious bug in the TableCombo widget in connection with misleading
selection change events being sent.
Hence, I'd apply for not reverting the change but fixing the present issue
on top of it.
Otherwise, we'd replace one bug simply with another (serious) one.

Best,
  MP

Am Mo., 9. Jan. 2023 um 10:25 Uhr schrieb Ajay Kumar <
***@***.***>:

**Comment by mpscholz** [comment]
In any case, we obviously lack unit tests for both use cases ...

Am Mo., 9. Jan. 2023 um 14:20 Uhr schrieb Matthias Paul Scholz <
***@***.***>:

**Comment by ajaylamba-provar** [comment]
Thanks for your input @mpscholz.

**Comment by lcaron** [comment]
Bug fixed in Nebula 3.1.1
