### ISSUE TITLE
RichTextPainter fails to render valid XHTML in case the QName has a namespace URI

### ISSUE THREAD

**Issue by jmauersberger** [EclipseNebula/nebula#500]
I stumbled over this when rendering XHTML from other sources. Lets say the XHTML starts with

`<div xmlns="http://www.w3.org/1999/xhtml">`

In that case code at 
https://github.com/eclipse/nebula/blob/2f10d093e081a0bdfef36716700b929f43e1876a/widgets/richtext/org.eclipse.nebula.widgets.richtext/src/org/eclipse/nebula/widgets/richtext/RichTextPainter.java#L231 will evaluate the QName.toString() value wich is `{http://www.w3.org/1999/xhtml}div` and obviously not `div` so any code after that wont work correctly. I guess a fix is pretty straight, just use `QName.getLocalPart()`, right? Or was that done by intention to ONLY parse XHTML without namespace?

**Comment by fipro78** [comment]
Well, the RichTextPainter was created as a renderer for content that was created by the RichTextEditor. I never came across a scenario where a namespace was included.

Was the code created this way by intention? Honestly I can't remember. We would need some extensive testing to ensure that the proposed fix does not break anything else.

**Comment by jmauersberger** [comment]
Thanks Dirk for the fast response. Well, we get these XHTML snippets from other tools like DNG, Codebeamer, Jama etc. they usually deliver bad or at least special HTML (although recently it looks as if some are using the same editing control that Nebula embeds). In the past it wasn't even sometimes real HTML. Anyway, looking at toString() which just concatenates the local part with the namespace, I bet its pretty much safe to rely on the local part only, at least that should be "backward compatible" and work as before for any kind of XHTML created by Nebula. I can offer help to work in this project but I first need to do some paperwork here on my end to be able to contribute to an OS project as this one.

**Comment by wimjongman** [comment]
Welcome, Jan.

**Comment by fipro78** [comment]
Fixed with https://github.com/eclipse/nebula/pull/506 

I did some testing and checked the implementation details. I did not see any side effects and the results look as expected.

Thanks for reporting and proposing a fix. Even it was only in textual form and not in form as a PR. :)

**Comment by jmauersberger** [comment]
Awesome, thanks Dirk. Actually I have a PR ready in our clone but legal did not yet gave me final confirmation so we could have contributed. You have been faster :-)
