### ISSUE TITLE
Use latest Tycho and Java 17 for building

### ISSUE THREAD

**Issue by vogella** [EclipseNebula/nebula#516]
The current build does not work with Java 17 locally (Tycho to old), would it be OK to update the GH to Java 17 and Tycho to the latest 3.0.4 release (which requires Java 17)?

I don't have write access to the Nebula Jenkins, so if Java runtime changes are requried on Jenkins, you would have to do it.

cc @wimjongman @lcaron

**Comment by merks** [comment]
Done via https://github.com/eclipse/nebula/issues/559
