### ISSUE TITLE
Resource leak in GeoMap widget when changing the tile server

### ISSUE THREAD

**Issue by bdaum** [EclipseNebula/nebula#517]
When setting a new tile server, the tile cache is cleared. But clearing the tile cache leaves the tile images undisposed.
Overriding the clear() method in the GeoMapHelper constructor fixes the problem:

		this.cache = Collections.synchronizedMap(new LinkedHashMap<TileRef, AsyncImage>(cacheSize, 0.75f, true) {
			@Override
			protected boolean removeEldestEntry(Map.Entry<TileRef, AsyncImage> eldest) {
				boolean remove = size() > GeoMapHelper.this.cacheSize;
				if (remove) {
					eldest.getValue().dispose();
				}
				return remove;
			}
			
			@Override
			public void clear() {
				for (AsyncImage image : values()) {
					image.dispose();
                                }
				super.clear();
			}
		});

**Comment by wimjongman** [comment]
Nice catch @bdaum Are you able to create a PR?

**Comment by lcaron** [comment]
@bdaum feel free to ask if you need any help

**Comment by bdaum** [comment]
Actually there is another glitch. The cache should be cleared when the GeoMapHelper instance is disposed:

	/**
	 * Dispose internal data
	 */
	public void dispose() {
		waitBackground.dispose();
		waitForeground.dispose();
		cache.clear();
	}

**Comment by lcaron** [comment]
Hi @bdaum 

Can you provide a patch through a pull request ? Do you need some help ?
