### ISSUE TITLE
MultiChoice<T> should support databindings

### ISSUE THREAD

**Issue by stereotron** [EclipseNebula/nebula#522]
In order to bind `org.eclipse.nebula.widgets.opal.multichoice.MultiChoice<T>` with Eclipse Databindings the methods
- List<<T>> getSelection();
- setSelection(Set<<T>>);
would need the same argument/return type otherwise it cant be bound using:
```
context.bindValue(
  PojoProperties.value("selection", List.class).observe(multiChoiceControl),
  PojoProperties.value("methods", List.class).observe(dataModel));
```
Currently this results in:
```
java.lang.IllegalArgumentException: Missing public setter method for selection property
	at org.eclipse.core.internal.databinding.beans.BeanPropertyHelper.writeProperty(BeanPropertyHelper.java:56)
```
Internally the selection is kept as a Set<T> so why not just return it as that?
The selection order is already lost through usage of the Set<T> and for that there would be getSelectionIndex().
Besides the API break I don't see a reason to not return a Set<T> with getSelection().

A temporary solution without breaking the API:

```
	public void setSelected(Set<T> selection) {
		setSelection(selection);
	}

	public Set<T> getSelected() {
		return this.selection;
	}
```

Getting access to the Text and the Button of MultiChoice would also be handy but thats not so important.

**Comment by wimjongman** [comment]
Please make a patch that does not break the API.

**Comment by wimjongman** [comment]
@stereotron are you going to supply this patch?

**Comment by stereotron** [comment]
> @stereotron are you going to supply this patch?

I'm sorry, I totally forgot about this. Here is the patch:
[nebula-multichoice-databinding.patch](https://github.com/eclipse/nebula/files/12740828/nebula-multichoice-databinding.patch)

It has getter and setter for the selection and additionally for the text control and the arrow button. This makes these controls available for customization.

**Comment by wimjongman** [comment]
Looks greate @stereotron can you make a Pull Request?

**Comment by stereotron** [comment]
It seems I have no permission to commit. 
Eclipse opens up a Login dialog which does not accept my github login credentials. 
Could you please commit this patch? This week I have no time to learn and use the workflow of this project.
![grafik](https://github.com/eclipse/nebula/assets/41795944/3333cac1-3a26-4b8f-9169-1129a29ca9c0)

**Comment by laeubi** [comment]
@stereotron in the eclipse UI you press the "fork" button, this will give you a private copy of this repository.

Then you cechkout your repository (maybe choose a different folder) and can push your changes there, then you will be given a link to pen a PR

**Comment by stereotron** [comment]
The process was a bit adventurous, but you should now have that pull request.

**Comment by wimjongman** [comment]
I do, thanks @stereotron. Much appreciated. I will release it as soon as the build comes back normally.
