### ISSUE TITLE
RichTextWidget: "special" characters lead to crash of widget if setText is used

### ISSUE THREAD

**Issue by ernstblechaPT** [EclipseNebula/nebula#523]
In the function [setText](https://github.com/eclipse/nebula/blob/74375d932ec3c0fd57b8bf602f4648a83b498c68/widgets/richtext/org.eclipse.nebula.widgets.richtext/src/org/eclipse/nebula/widgets/richtext/RichTextEditor.java#L416) a javascript command is build via string concatenation.

If the user supplied string contains unescaped characters (e.g. `'`) this leads to the user supplied string being executed by the browser context. In most cases this leads to a crash of the javascript interpreter.

The same problem also applies to [insertText](https://github.com/eclipse/nebula/blob/74375d932ec3c0fd57b8bf602f4648a83b498c68/widgets/richtext/org.eclipse.nebula.widgets.richtext/src/org/eclipse/nebula/widgets/richtext/RichTextEditor.java#L434) and [insertHTML](https://github.com/eclipse/nebula/blob/74375d932ec3c0fd57b8bf602f4648a83b498c68/widgets/richtext/org.eclipse.nebula.widgets.richtext/src/org/eclipse/nebula/widgets/richtext/RichTextEditor.java#L444).

**Comment by fipro78** [comment]
Thanks for providing the PR. Looks good to me, so I merged it.
