### ISSUE TITLE
Nebula download page out of date

### ISSUE THREAD

**Issue by tito-cu** [EclipseNebula/nebula#525]
From https://projects.eclipse.org/projects/technology.nebula when trying to download the latest Nebula widgets version (https://projects.eclipse.org/projects/technology.nebula/downloads), the page redirects to https://eclipse.dev/nebula/downloads.php which is out of date as the latest released Nebula version is 3.0.0. and not 2.7.2 like the page states (source: https://github.com/eclipse/nebula/releases)

**Comment by wimjongman** [comment]
Thanks, the website was updated but it does not sync. I have filed an issue for the webmasters here:

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3699

**Comment by lcaron** [comment]
Thank you @wimjongman

**Comment by wimjongman** [comment]
Fixed. Thanks for reporting.
