### ISSUE TITLE
Push the new release to Dec 25

### ISSUE THREAD

**Issue by wimjongman** [EclipseNebula/nebula#526]
We did not make the release date. Release is pushed to dec 25.

**Comment by lcaron** [comment]
Hi

I've been very sick that last months so I miss the date. I have to look at issues and see what to do.

**Comment by wimjongman** [comment]
Hey Laurent. I'm sorry to hear that. Let me take care of it when you are not feeling well.

**Comment by lcaron** [comment]
You're right, I should have done that.
