### ISSUE TITLE
Floating Text Label does not fit when display is scaled

### ISSUE THREAD

**Issue by wimjongman** [EclipseNebula/nebula#532]
On high resolution displays, scaling causes the Floating Text label to be misaligned.

![image](https://github.com/eclipse/nebula/assets/180969/2de9bd9d-b3d7-4525-8c9e-f5fa31ea4e7b)

**Comment by wimjongman** [comment]
This was fixed:

![image](https://github.com/eclipse/nebula/assets/180969/a8d863a7-271a-43a0-8589-25226714dba8)

**Comment by lcaron** [comment]
Thank you wim.
