### ISSUE TITLE
Is widgets/grid/org.eclipse.nebula.jface.gridviewer alive/still needed?

### ISSUE THREAD

**Issue by hannibal218bc** [EclipseNebula/nebula#538]
I've noticed that there is apparently duplicate code for the Java package `org.eclipse.nebula.jface.gridviewer` living at these locations:
- https://github.com/eclipse/nebula/tree/a0009fde4f696501c3dcf7cf0488761406f0350e/widgets/grid/org.eclipse.nebula.jface.gridviewer/src/org/eclipse/nebula/jface/gridviewer
- https://github.com/eclipse/nebula/tree/a0009fde4f696501c3dcf7cf0488761406f0350e/widgets/grid/org.eclipse.nebula.widgets.grid/src/org/eclipse/nebula/jface/gridviewer

It seems the latest commits have only touched the copy in `widgets/grid/org.eclipse.nebula.grid`; and also it seems there is no release artifact generated from `widgets/grid/org.eclipse.nebula.jface.gridviewer` in e.g. [Nebula 3.0.0](https://download.eclipse.org/nebula/releases/3.0.0/plugins/).

So... could and should `widgets/grid/org.eclipse.nebula.jface.gridviewer` be removed?

I've stumbled upon this while porting a feature I patched many years ago into Nebula's and Eclipse RAP's Grid controls to add dynamic, aggregated footers (https://www.eclipse.org/lists/nebula-dev/msg01324.html and https://bugs.eclipse.org/bugs/show_bug.cgi?id=333471), noticing that there are currently two files for the `GridTreeViewer` and `GridTableViewer` classes, which seems odd.

Thanks!

**Comment by lcaron** [comment]
Project Removed in Nebula 3.1.1
