### ISSUE TITLE
Fix Code Scanning Alerts

### ISSUE THREAD

**Issue by lcaron** [EclipseNebula/nebula#540]
Fix code scanning alerts (cf. https://github.com/eclipse/nebula/security/code-scanning)

**Comment by lcaron** [comment]
Fixed in release 3.1.0

**Comment by marcolopes** [comment]
What's this? (Code Scanning!)

The URL is broken: https://github.com/eclipse/nebula/security/code-scanning

**Comment by laeubi** [comment]
> What's this? (Code Scanning!)

https://docs.github.com/en/code-security/code-scanning/introduction-to-code-scanning/about-code-scanning

> The URL is broken

You can only see it if you have write access to the repository
