### ISSUE TITLE
Open the NebulaSlider to allow user extension

### ISSUE THREAD

**Issue by jdumont-a4t** [EclipseNebula/nebula#550]
Hi,

We want to use the NebulaSlider component in one of our projects, but we'll need to modify its style so that it integrates with our Eclipse RCP application. At the moment, this isn't possible because the member variables are 'private final' and the methods for drawing the component are in 'private' too. 

Would it be possible to allow the customisation of the slider by opening the elements with specific methods, or by allowing them to be overridden by inheritance by passing them as protected?

Thanks for your feedback.

**Comment by lcaron** [comment]
The graphical information are now handled by a renderer that could be customized 

![image](https://github.com/eclipse/nebula/assets/1170014/6d09236a-d3d5-4741-9ca0-bfbe8d9bf2d2)

Please check the example located at : https://github.com/eclipse/nebula/blob/master/widgets/nebulaslider/org.eclipse.nebula.widgets.nebulaslider.snippets/src/org/eclipse/nebula/widgets/opal/nebulaslider/snippets/NebulaSliderSnippetOtherRenderer.java

Hope you'll enjoy ;)

**Comment by lcaron** [comment]
It's not a renderer, it is a "graphic configuration"

**Comment by jdumont-a4t** [comment]
Thanks a lot for your help, it seems that it will answer to my needs. 
I can't wait to deploy the new version !
