### ISSUE TITLE
Transform not disposed on the AnalogClockPainter 

### ISSUE THREAD

**Issue by jdumont-a4t** [EclipseNebula/nebula#556]
In the AnalogClockPainter class, it seems that a created Transform is never disposed :
(line 83) Transform o = new Transform(e.display);

May this can be corrected in the 3.1.1 ?

**Comment by lcaron** [comment]
Bug fixed in Nebula 3.1.1 :)

Thank you for reporting, and feel free to contribute to Nebula.

**Comment by vsennedot** [comment]
It seems that removing the Transform causes problems: the AM/PM button is not visible and the current date panel follows the angle of the hour hand.
