### ISSUE TITLE
Treemapper general usability improvments

### ISSUE THREAD

**Issue by gion86** [EclipseNebula/nebula#560]
I'm using the treemapper widget in one of my projects, and I've made some small usability improvements. Most of them are about dynamic configuration of the widget behaviour:

- `ISemanticTreeMapperSupport.java`: method to enable or disable the warning in case of fail in item resolution
- `TreeMapperUIConfigProvider.java`: support for "drag and drop" enable and custom weights for the tree's control layout
- `TreeMapper.java`: method to update the canvas draw, offset for tree mapping drawing based on the tree header height

I will make a PR for this.

Thankyou!
Gionata

**Comment by lcaron** [comment]
Hi Gionata 

Welcome on board !

I'll have a look at this PR.
