### ISSUE TITLE
Grid cells not showing on Mac if setRowHeaderVisible(true) called before creating columns

### ISSUE THREAD

**Issue by Phillipus** [EclipseNebula/nebula#573]
This is a problem again on Mac. See https://github.com/eclipse/nebula/pull/190

macOS 14.4 Sonoma
Eclipse SWT 3.125.0.v20240227-1638

On Mac run [GridViewerSnippet1](https://github.com/eclipse/nebula/blob/master/examples/org.eclipse.nebula.snippets/src/org/eclipse/nebula/snippets/grid/viewer/GridViewerSnippet1.java) 

It looks like this:

<img width="1012" alt="Screenshot 2024-03-13 at 15 35 21" src="https://github.com/eclipse/nebula/assets/600504/0ac68c09-3f80-4d17-816b-c074578576a5">

Now move this line to line 189 so it is called _after_ creating the `GridColumns`:

https://github.com/eclipse/nebula/blob/7679ef64ea4378bdc66abf61f23705ddc083ee62/examples/org.eclipse.nebula.snippets/src/org/eclipse/nebula/snippets/grid/viewer/GridViewerSnippet1.java#L139

And it is OK:

<img width="1012" alt="Screenshot 2024-03-13 at 15 37 30" src="https://github.com/eclipse/nebula/assets/600504/7d251dd4-9295-4ab7-9dcd-f5bfce05a1d7">

**Comment by Phillipus** [comment]
As an experiment, if I remove this line it works OK:

https://github.com/eclipse/nebula/blob/7679ef64ea4378bdc66abf61f23705ddc083ee62/widgets/grid/org.eclipse.nebula.widgets.grid/src/org/eclipse/nebula/widgets/grid/GridColumn.java#L425

The condition is not met because `parent.getClientArea().height` is returning 0.

**Comment by lcaron** [comment]
Hello Phil

If you change the line 425 by this one is it better ?

if (IS_MAC && availableVisibleWidthForColumns == 1 && (parent.getClientArea().height == 1 || parent.getClientArea().height == 0))

(I think that the behaviour depends on the version of MacOs)

**Comment by Phillipus** [comment]
> If you change the line 425 by this one is it better ?

Yes, because `parent.getClientArea().height` is returning 0.

> (I think that the behaviour depends on the version of MacOs)

I think you may be right because this used to work, I think.

**Comment by lcaron** [comment]
Bug fixed in Nebula 3.2.0
