### ISSUE TITLE
No repositories for explicit versions on download.eclipse.org

### ISSUE THREAD

**Issue by fipro78** [EclipseNebula/nebula#586]
Hi,

I noticed that we do no provide update sites for explicit versions via https://download.eclipse.org/nebula/releases/ anymore. There is only the **latest** update site available.

I noticed this because suddenly my builds broke, because https://download.eclipse.org/nebula/releases/3.1.0 is not available anymore. I needed to switch to https://archive.eclipse.org/nebula/releases/3.1.0

I understand that download.eclipse.org should be kept clean, and older releases should be moved to archive.eclipse.org. But moving all versions, even the most current ones there, without a copy on download.eclipse.org is quite unfortunate. IIRC download.eclipse.org provides better download statistics. And as a project we should at least provide the last two or three versions via download.eclipse.org, so that users have the chance to update by intention, not by accident if they are forced to use the **latest** update site.

Was the move of all versioned update sites to archive.eclipse.org done by intention or by accident?

**Comment by laeubi** [comment]
Regardless of the move itself, should it not automatically redirect to the archive (it seems to be the case in the past).

**Comment by merks** [comment]
Yes, the cleanup was intentional.

The update sites are all moved to here:

  https://download.eclipse.org/nebula/updates/

And yes, the site https://download.eclipse.org/nebula/releases/3.1.0 should and does load properly via automatic redirection by download.eclipse.org server:

![image](https://github.com/eclipse/nebula/assets/208716/3bbf5730-67a4-4b24-9fd2-792872dcbc10)

**Comment by fipro78** [comment]
OK, thanks for the information. Somehow the redirection did not work yesterday, but does today.

If it is by intention, the ticket can be closed. Sorry for the noise.
