### ISSUE TITLE
Treemapper does not display links

### ISSUE THREAD

**Issue by Boarschti42** [EclipseNebula/nebula#601]
Hey there, 
We implemented Nebula Treemapper in an OSGI E4 application. We are facing the issue, that the component is rendered and filled (right and left pane), but there is no way to draw the mapping links via mouse drag and drop. We are using latest nebula release on top of eclipse 2023-06. 
Sources can be found here: [webshop mapping](https://bitbucket.org/fakturamadev/fakturama-2/src/f48ede7f979ae134eb9c4d48f240ca035228a5fe/Fakturama-Parent/com.sebulli.fakturama.rcp/src/main/java/com/sebulli/fakturama/dialogs/WebShopStatusSettingsDialog.java?at=feature%2Fboarschti%2Fupdate_java_17)

Are there any recommendations to fix it?

Thanks

**Comment by lcaron** [comment]
I'll have a look

**Comment by Boarschti42** [comment]
Thank you, there is also a beta release, where you can see it working:  [link to beta download](https://www.fakturama.info/neue-betaversion-online/)

where to go: Preferences -> Webshop -> button Status Mapping

edit: my main issue was Windows version :D

**Comment by Boarschti42** [comment]
Is there any progress here available?

**Comment by wimjongman** [comment]
Please provide a minimal snippet where the issue can be seen. This is a very small java class with a main method as we can see here:


https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/examples/org.eclipse.swt.snippets/Snippets.md

**Comment by wimjongman** [comment]
@Boarschti42 are you going to supply the requested snippet or can we close the issue?

**Comment by Boarschti42** [comment]
Hi, will do it this weekend i think. Didnt have had time to code it for this purpose.

**Comment by wimjongman** [comment]
No progress. Closing.
