### ISSUE TITLE
TitledSeparator shows no separator on linux

### ISSUE THREAD

**Issue by laeubi** [EclipseNebula/nebula#606]
This is how the [example snippet](https://github.com/eclipse/nebula/tree/master/widgets/opal/titledseparator/org.eclipse.nebula.widgets.opal.titledseparator.snippets/src/org/eclipse/nebula/widgets/opal/titledseparator/snippets) looks on linux:

![grafik](https://github.com/user-attachments/assets/7dcc094d-a00b-4b39-9baf-f38e64913f41)

the [examples page](https://wiki.eclipse.org/Nebula_TitledSeparator) say it should look like this:

![grafik](https://github.com/user-attachments/assets/476d7c35-62ee-4764-83bb-70b41fb58bf8)

**Comment by wimjongman** [comment]
This is a different behavior of SWT.

I think we can add SWT.SHADOW_OUT to get the desired effect on all platforms.

``` java
	/**
	 * Create a separator
	 */
	private void createSeparator() {
		final Label separator = new Label(this, SWT.SEPARATOR | SWT.HORIZONTAL | SWT.SHADOW_OUT);
		separator.setLayoutData(new GridData(GridData.FILL, GridData.CENTER, true, false));
		separator.setBackground(getBackground());
	}
```

![image](https://github.com/user-attachments/assets/0ea84eca-3e4c-4ef0-bad6-f9ff57726607)
