### ISSUE TITLE
FormattedText.MaskFormatter Regression

### ISSUE THREAD

**Issue by claussenj** [EclipseNebula/nebula#608]
Dear Nebula team,

we have run into a regression of the MaskFormatter in the FormattedText widget:

The getValue() is intended to return the actual text field value without the separator characters. But this behavior was broken in this line:

https://github.com/eclipse/nebula/blob/31f40e4e56e006f54e87eae14b23c36dbd79f09b/widgets/formattedtext/org.eclipse.nebula.widgets.formattedtext/src/org/eclipse/nebula/widgets/formattedtext/MaskFormatter.java#L153

The last comparison should also test for equality:
c == P_LHEXDIGIT

Such that the complete if condition would read:
			if (c == P_DIGIT || c == P_ALPHANUM || c == P_UPPERCASE
					|| c == P_LOWERCASE || c == P_UHEXDIGIT || c == P_LHEXDIGIT) {

Could you please fix this?

regards
Jens

**Comment by wimjongman** [comment]
Jens, can you make a PR?

**Comment by claussenj** [comment]
Hi @wimjongman ,

here is a PR: https://github.com/EclipseNebula/nebula/pull/624

Seems like I have failed to add a proper footer for the ECA to the PR, not sure if it is usable...

My Eclipse ID would be jclaussen, with a signed ECA.

regards
Jens

**Comment by wimjongman** [comment]
Thanks, Jens!

**Comment by lcaron** [comment]
Thanks @claussenj and @wimjongman
