### ISSUE TITLE
RichTextEditor does not support MouseListener

### ISSUE THREAD

**Issue by huthomas** [EclipseNebula/nebula#609]
After adding a `MouseListener` to the `RichTextEditor` the methods are never called. 

There is no javascript function registered that would pass such events to java `mouseDown` and `mouseDoubleClick` methods.

Is there a reason why that is not implemented? Or are there plans to implement this functionality?

**Comment by fipro78** [comment]
I guess there was never a requirement for adding it. At least I can't remember. And I am not sure if we could pass the correct information from the browser to the swt layer.

If you have an idea how to implement it, feel free to create a PR. There are no plans for any improvement of this control at the moment.

**Comment by huthomas** [comment]
Thanks for the info.
