### ISSUE TITLE
https://eclipse.dev/nebula/downloads.php outdated

### ISSUE THREAD

**Issue by vogella** [EclipseNebula/nebula#614]
https://eclipse.dev/nebula/downloads.php is outdated, still taking about an upcoming release in Feb 2024.

Maybe you can retire this page and just point to Github for the releases?

**Comment by wimjongman** [comment]
Fixed with https://github.com/eclipse/nebula-website/commit/2d5b88797fec51dae4d57c7b883088c61e65064c

**Comment by vogella** [comment]
Thanks @wimjongman
