### ISSUE TITLE
Requirement for Split Button with Toggle Behaviour

### ISSUE THREAD

**Issue by IanMayo** [EclipseNebula/nebula#9]
A Split Button is a Push Button that also contains a drop-down menu.

The drop-down menu typically contains modifiers for how the push button action is performed.  In this example the UI allows the user to change what kind of search is performed:

![image](https://user-images.githubusercontent.com/1108513/46465793-775d0300-c7c1-11e8-8ab1-450b03d6f0be.png)

Sadly in the JFace Action implementation, SWT.CHECK and SWT.DROP_DOWN are mutually exclusive: 
````
	/**
	 * Creates a new action with the given text and style.
	 *
	 * @param text
	 *            the action's text, or <code>null</code> if there is no text
	 * @param style
	 *            one of <code>AS_PUSH_BUTTON</code>,
	 *            <code>AS_CHECK_BOX</code>, <code>AS_DROP_DOWN_MENU</code>,
	 *            <code>AS_RADIO_BUTTON</code>, and
	 *            <code>AS_UNSPECIFIED</code>.
	 */
	protected Action(String text, int style) {
		this(text);
		switch (style) {
		case AS_PUSH_BUTTON:
			value = VAL_PUSH_BTN;
			break;
		case AS_CHECK_BOX:
			value = VAL_TOGGLE_BTN_OFF;
			break;
		case AS_DROP_DOWN_MENU:
			value = VAL_DROP_DOWN_MENU;
			break;
		case AS_RADIO_BUTTON:
			value = VAL_RADIO_BTN_OFF;
			break;
		}
	}
````

On first impression it looks like a new version of JFAce Action is required, though maybe there's another strategy.

**Comment by wimjongman** [comment]
This is the style for the top level button. Inside it is possible to have check or toggle. 

Why did you file this issue here?

![image](https://user-images.githubusercontent.com/180969/46583566-8827a600-ca59-11e8-98f9-f21ef2330fc4.png)

**Comment by IanMayo** [comment]
I believe that SWT doesn't currently have a button that can provided `Toggle` _and_ `Drop-down` behaviour.   i.e. a button that has on/of states, that also has a drop-down menu to further customise the operation.

I'm coarsely simulating the behaviour by manually change the button icon to show a selected state, but it doesn't match the look & feel of other toggle buttons.

I posted it here for two reasons:
1. To invite an Eclipse UI expert to correct my mistake, and highlight how it is possible to get the required UI
2. To see if there's any wider interest in such a control, sufficient to justify creation of such a control for the Nebula project.

Fortunately, @lcaron has been in contact regarding the latter.

@wimjongman - this seemed the correct place to post this issue, following the closure of the forum.  Was I mistaken?

**Comment by wimjongman** [comment]
It looked like you described a bug in JFace. Did you ask in SWT and JFace the possibility to add this behavior?

**Comment by IanMayo** [comment]
Aah, @wimjongman - thanks for the advice. I mistakenly viewed JFace as an immovable beast, with Nebula the pragmatic way to get new UI features.  I'll post the issue in JFace forum.

**Comment by IanMayo** [comment]
Issue submitted to JFace forum:
https://www.eclipse.org/forums/index.php/t/1095514/

**Comment by wimjongman** [comment]
Hey Ian,

I’m sorry to let you jump thru hoops but it ia best if you would directly file a bug against jface in Bugzilla.

**Comment by IanMayo** [comment]
Ok @wimjongman  - it really is a lot of work for newbies :-)

Reported:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=539914

**Comment by wimjongman** [comment]
I know. Please be persistent.

**Comment by lcaron** [comment]
I've developped a custom SplitButton in the past... It is based on a SWT BUTTON and I draw the separator and the arrow on it.

@wimjongman What do you think about this idea ?

**Comment by wimjongman** [comment]
That's nice. I would like to see that code.

**Comment by IanMayo** [comment]
@wimjongman - I've now reflected on the issue, and added a comment to the bug:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=539914

Significantly, this seems a JFace issue that can't be resolved through provision a custom Nebula widget.  In an RCP toolbar, we just add JFace Action instances, with a status bit that indicates how the control should be rendered.  I realise I need to first modify JFace Action to allow multiple status bits (toggle AND drop-down), then provide an implementation of those multiple-state bits.

I'm pretty sure that's beyond Nebula.

**Comment by lcaron** [comment]
Close this bug because I think it is concerning SWT/JFace and not Nebula.
Ian, you can reopen this bug if necessary.
